package controllers

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/geekgonecrazy/capsule/boot"
	"github.com/geekgonecrazy/capsule/core/install"
	capsulev1 "github.com/geekgonecrazy/capsule/models/capsule/v1"
)

// InstallController implements capsule.v1.InstallServiceServer. It is
// only registered when capsuled is in installer mode (USB-booted on a
// machine with a viable internal target). On a runtime capsule the
// controller is absent and clients receive Unimplemented.
type InstallController struct {
	capsulev1.UnimplementedInstallServiceServer

	// ShortID is the installer capsule's own short handle. Distinct
	// from the disk-booted capsule's short_id, which is generated by
	// Install. Surfaced via Status so the CLI can confirm it's talking
	// to the right installer.
	ShortID string
	// CapsuleID is the installer's own identity UUID. Same caveat.
	CapsuleID string
	// Version is the capsuled build identifier. The disk-booted
	// capsule will run the same binary.
	Version string
	// USBBootDisk is the device the installer is running from
	// ("/dev/sda"). The Install RPC copies partitions from this disk
	// onto the target.
	USBBootDisk string
	// Targets is the candidate internal disks computed by boot.DetectInstallerMode.
	Targets []boot.TargetDisk
}

// Status reports installer-mode metadata. Pre-adoption, unauthenticated.
func (c *InstallController) Status(_ context.Context, _ *capsulev1.InstallStatusRequest) (*capsulev1.InstallStatusResponse, error) {
	if len(c.Targets) == 0 {
		return nil, status.Error(codes.FailedPrecondition, "no candidate target disks")
	}
	paths := make([]string, 0, len(c.Targets))
	for _, t := range c.Targets {
		paths = append(paths, t.Path)
	}
	return &capsulev1.InstallStatusResponse{
		ShortId:         c.ShortID,
		CapsuleId:       c.CapsuleID,
		TargetDisk:      c.Targets[0].Path,
		TargetSizeBytes: c.Targets[0].SizeBytes,
		Targets:         paths,
		Version:         c.Version,
	}, nil
}

// Install drives the disk write and seal-during-install. Server-streams
// InstallProgress messages; the terminal "done" event carries the
// disk-booted capsule's future identity in InstallResult.
func (c *InstallController) Install(req *capsulev1.InstallRequest, stream capsulev1.InstallService_InstallServer) error {
	if c.USBBootDisk == "" {
		return status.Error(codes.FailedPrecondition, "installer has no source disk; cannot flash")
	}
	if len(c.Targets) == 0 {
		return status.Error(codes.FailedPrecondition, "no candidate target disks")
	}

	send := func(phase string, percent uint32, message string) {
		_ = stream.Send(&capsulev1.InstallProgress{
			Phase:   phase,
			Percent: percent,
			Message: message,
		})
	}

	installer := &install.Installer{
		USBBootDisk: c.USBBootDisk,
		Targets:     c.Targets,
	}
	result, err := installer.Run(stream.Context(), install.Request{
		TargetDisk:     req.GetTargetDisk(),
		OperatorPubkey: req.GetOperatorPubkey(),
		OperatorName:   req.GetOperatorName(),
		// Default to true: the proto default for bool is false, but
		// the operator-driven UX puts the operator key in every flow
		// unless they explicitly --no-seal. The CLI always sets seal
		// explicitly; if a caller omits it, treat as seal=true.
		Seal: req.GetSeal() || len(req.GetOperatorPubkey()) > 0,
	}, send)
	if err != nil {
		return status.Errorf(codes.Internal, "install failed: %v", err)
	}

	// Terminal done event with the future disk identity.
	if err := stream.Send(&capsulev1.InstallProgress{
		Phase:   "done",
		Percent: 100,
		Message: "install complete; remove USB and power-cycle",
		Result: &capsulev1.InstallResult{
			CapsuleId:            result.CapsuleID,
			TlsFingerprintSha256: result.TLSFingerprintSha256,
			Kid:                  result.Kid,
			ShortId:              result.ShortID,
		},
	}); err != nil {
		return err
	}
	return nil
}
