package install

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/geekgonecrazy/capsule/auth"
	"github.com/geekgonecrazy/capsule/boot"
)

// FirstBootBundle is the JSON written to the target disk's PERM
// partition during a sealed install. On first boot from the disk,
// capsuled detects this file, ingests it into the freshly-initialized
// SQLite database, drops the file, and skips opening a claim window.
// Result: a single-operator-pass install with no second adopt.
type FirstBootBundle struct {
	// CapsuleID is the UUID the disk will use as its stable identity.
	// Pre-generated by the installer so the operator's context entry
	// pins it before the disk has booted.
	CapsuleID string `json:"capsule_id"`
	// ShortID is derived from CapsuleID at install time and persisted
	// so the disk-booted capsule doesn't have to recompute it (and
	// could in theory differ if we ever change the derivation).
	ShortID string `json:"short_id"`
	// TLSCertPEM is the disk's leaf certificate. Together with
	// TLSKeyPEM, this is what the disk-booted capsule presents on its
	// first TLS handshake; the operator's context pins its fingerprint.
	TLSCertPEM string `json:"tls_cert_pem"`
	// TLSKeyPEM is the matching private key. Sensitive — written
	// 0600 by the install path and ingested as the disk's
	// /perm/tls/server.key on first boot.
	TLSKeyPEM string `json:"tls_key_pem"`
	// OperatorPubkey is the raw 32-byte Ed25519 public key (base64-
	// encoded for JSON). Becomes the first row in authorized_keys on
	// the disk, so subsequent operator RPCs work without an Adopt.
	OperatorPubkey string `json:"operator_pubkey"`
	// OperatorName is the friendly label stored alongside the key
	// ("nuc-1"). Surfaced by `capsulectl whoami` after first boot.
	OperatorName string `json:"operator_name"`
}

// Request captures the operator-supplied side of an install. Defaults
// match the gRPC InstallRequest.
type Request struct {
	TargetDisk     string
	OperatorPubkey []byte // raw 32-byte Ed25519
	OperatorName   string
	Seal           bool   // when false, no firstboot.json is written
}

// Result is what the disk-booted capsule will look like once the USB is
// removed and the machine reboots. Returned by Run; surfaced to the
// CLI in the terminal InstallProgress message.
type Result struct {
	CapsuleID            string
	ShortID              string
	TLSFingerprintSha256 string
	Kid                  string
}

// ProgressFn receives phase updates from Run. percent is 0..100 and
// resets on each new phase. message may be empty between ticks.
type ProgressFn func(phase string, percent uint32, message string)

// Installer drives one install. Construct one per InstallService.Install
// RPC; it holds no goroutines and is safe to discard after Run returns.
type Installer struct {
	// USBBootDisk is the device we copy the source partitions from
	// ("/dev/sda"). Resolved by boot.BootDisk() before the installer
	// is constructed.
	USBBootDisk string
	// Targets are the candidate disks reported by mode detection.
	// Used to validate Request.TargetDisk; refusing a target not in
	// this list catches an operator typo before any destructive write.
	Targets []boot.TargetDisk
}

// Run executes the full install pipeline. Each phase reports progress
// via fn; the final "done" phase is emitted by the caller (the
// controller streaming the gRPC response) once Result is in hand.
//
// On any error, Run returns without rolling back partial writes — the
// USB is unaffected and the operator can re-run install. v1 does not
// implement automatic cleanup of partial target writes; a failed
// install leaves the target disk in whatever intermediate state Run
// stopped at.
func (i *Installer) Run(ctx context.Context, req Request, fn ProgressFn) (*Result, error) {
	if fn == nil {
		fn = func(string, uint32, string) {}
	}

	// --- verify ---
	fn("verify", 0, "checking target disk")
	target, err := i.resolveTarget(req.TargetDisk)
	if err != nil {
		return nil, err
	}
	if i.USBBootDisk == "" {
		return nil, fmt.Errorf("installer has no source boot disk")
	}
	if i.USBBootDisk == target.Path {
		return nil, fmt.Errorf("refusing to install onto the boot disk %s", target.Path)
	}
	fn("verify", 100, fmt.Sprintf("target=%s (%d bytes)", target.Path, target.SizeBytes))

	layout, err := LayoutForDisk(target.SizeBytes)
	if err != nil {
		return nil, fmt.Errorf("layout: %w", err)
	}

	// --- partition ---
	fn("partition", 0, "writing MBR")
	if err := WriteMBR(target.Path, layout); err != nil {
		return nil, err
	}
	if err := rereadPartitions(target.Path); err != nil {
		// Best-effort: partprobe-equivalent. If it fails, mount steps
		// later will fail loudly anyway. Don't abort here.
		fn("partition", 100, "warning: kernel re-read failed: "+err.Error())
	} else {
		fn("partition", 100, "partition table written")
	}

	// USB partition device paths. The boot disk's partitions are at
	// e.g. /dev/sda1, /dev/sda2 (for sata/usb) or /dev/nvme0n1p1 (for
	// nvme — though USB-installed nvme is rare). partitionPath handles
	// both naming conventions.
	usbBoot := partitionPath(i.USBBootDisk, 1)
	usbSlotA := partitionPath(i.USBBootDisk, 2)
	tgtBoot := partitionPath(target.Path, 1)
	tgtSlotA := partitionPath(target.Path, 2)
	tgtSlotB := partitionPath(target.Path, 3)
	tgtPerm := partitionPath(target.Path, 4)

	// --- write_boot ---
	if err := waitForPath(tgtBoot, 5*time.Second); err != nil {
		return nil, fmt.Errorf("waiting for %s: %w", tgtBoot, err)
	}
	if err := CopyPartition(usbBoot, 0, tgtBoot, 0, layout.BootSectors, copyProgress(fn, "write_boot")); err != nil {
		return nil, fmt.Errorf("copy boot: %w", err)
	}
	// The USB installer's grub.cfg references PARTUUID=b005ab1e (installer
	// disk sig). The NVMe was just stamped with b1a570ff (runtime sig), so
	// the copied grub.cfg would cause a boot failure. Patch it, and also
	// seed vmlinuz_b + initramfs_b — the installer image only carries slot_a.
	fn("patch_boot", 0, "patching grub.cfg for runtime disk + seeding slot_b kernel")
	if err := patchBootGrubCfg(tgtBoot); err != nil {
		return nil, fmt.Errorf("patch boot: %w", err)
	}
	fn("patch_boot", 100, "grub.cfg patched")

	// --- write_slot_a ---
	if err := waitForPath(tgtSlotA, 5*time.Second); err != nil {
		return nil, fmt.Errorf("waiting for %s: %w", tgtSlotA, err)
	}
	if err := CopyPartition(usbSlotA, 0, tgtSlotA, 0, layout.SlotASectors, copyProgress(fn, "write_slot_a")); err != nil {
		return nil, fmt.Errorf("copy slot_a: %w", err)
	}

	// --- write_slot_b ---
	// Both slots seed from the USB's slot_a — they're identical on a
	// fresh install. Updates diverge them later via UpdateOS.
	if err := waitForPath(tgtSlotB, 5*time.Second); err != nil {
		return nil, fmt.Errorf("waiting for %s: %w", tgtSlotB, err)
	}
	if err := CopyPartition(usbSlotA, 0, tgtSlotB, 0, layout.SlotBSectors, copyProgress(fn, "write_slot_b")); err != nil {
		return nil, fmt.Errorf("copy slot_b: %w", err)
	}

	// --- init_lvm ---
	fn("init_lvm", 0, "creating PV + VG + meta LV on "+tgtPerm)
	if err := waitForPath(tgtPerm, 5*time.Second); err != nil {
		return nil, fmt.Errorf("waiting for %s: %w", tgtPerm, err)
	}
	if err := initTargetLVM(tgtPerm); err != nil {
		return nil, fmt.Errorf("init lvm: %w", err)
	}
	fn("init_lvm", 100, "PV + VG + meta + thinpool created")

	// --- seal_firstboot ---
	result := &Result{}
	if req.Seal && len(req.OperatorPubkey) > 0 {
		fn("seal_firstboot", 0, "generating disk identity + sealing operator key")
		bundle, err := i.buildFirstBootBundle(req)
		if err != nil {
			return nil, err
		}
		if err := writeFirstBootBundle(bundle); err != nil {
			return nil, fmt.Errorf("write firstboot bundle: %w", err)
		}
		result.CapsuleID = bundle.CapsuleID
		result.ShortID = bundle.ShortID
		// Compute fingerprint + kid for the result, even though they
		// were also derived inside buildFirstBootBundle.
		fp, err := fingerprintFromPEM(bundle.TLSCertPEM)
		if err != nil {
			return nil, err
		}
		result.TLSFingerprintSha256 = fp
		result.Kid = auth.KidFromPubkey(req.OperatorPubkey)
		fn("seal_firstboot", 100, "firstboot.json written")
	} else {
		fn("seal_firstboot", 100, "seal=false; disk will open a claim window on first boot")
	}

	// --- sync ---
	fn("sync", 0, "flushing buffers")
	_ = exec.Command("/bin/sync").Run()
	// Deactivate the target VG so a subsequent re-install (or USB
	// reboot) doesn't see two VGs named "capsule" — the installer's
	// own VG is on the USB.
	if err := exec.Command("/sbin/vgchange", "-an", "capsule").Run(); err != nil {
		// Non-fatal: vgchange will sometimes refuse if the installer's
		// own VG is named capsule (same disk-label scheme). The disk
		// is fully written at this point; deactivation is hygiene.
		fn("sync", 50, "warning: vgchange -an failed: "+err.Error())
	}
	fn("sync", 100, "")
	return result, nil
}

// resolveTarget picks the target disk. Empty → first candidate.
// Non-empty → must match one of the candidates (avoids a typo wiping
// the wrong disk).
func (i *Installer) resolveTarget(req string) (boot.TargetDisk, error) {
	if len(i.Targets) == 0 {
		return boot.TargetDisk{}, fmt.Errorf("no candidate target disks")
	}
	if req == "" {
		return i.Targets[0], nil
	}
	for _, t := range i.Targets {
		if t.Path == req {
			return t, nil
		}
	}
	avail := make([]string, 0, len(i.Targets))
	for _, t := range i.Targets {
		avail = append(avail, t.Path)
	}
	return boot.TargetDisk{}, fmt.Errorf("target %s not a viable candidate (available: %s)",
		req, strings.Join(avail, ", "))
}

// buildFirstBootBundle pre-generates the disk's future identity and
// packs it together with the operator's pubkey.
func (i *Installer) buildFirstBootBundle(req Request) (*FirstBootBundle, error) {
	capsuleID := uuid.NewString()
	shortID := deriveShortID(capsuleID)
	certPEM, keyPEM, _, err := auth.GenerateCertPEM(capsuleID)
	if err != nil {
		return nil, fmt.Errorf("generate tls: %w", err)
	}
	return &FirstBootBundle{
		CapsuleID:      capsuleID,
		ShortID:        shortID,
		TLSCertPEM:     string(certPEM),
		TLSKeyPEM:      string(keyPEM),
		OperatorPubkey: base64.StdEncoding.EncodeToString(req.OperatorPubkey),
		OperatorName:   req.OperatorName,
	}, nil
}

// deriveShortID mirrors capsuled/main.go's derivation. Duplicated here
// rather than imported to keep core/install free of cmd/ imports.
// "capsule-" + first 2 bytes of the UUID in hex.
func deriveShortID(capsuleID string) string {
	u, err := uuid.Parse(capsuleID)
	if err != nil {
		return ""
	}
	return fmt.Sprintf("capsule-%02x%02x", u[0], u[1])
}

// writeFirstBootBundle initializes the target PERM's meta LV and writes
// /perm/firstboot.json onto it. The LV is unmounted before return so
// the disk's own first-boot path can mount it cleanly.
//
// Path conventions match boot/boot_linux.go's mountPerm:
//   /dev/capsule/meta is the ext4 LV that becomes /perm on the disk.
//   /perm/firstboot.json is what boot_linux.go ingests on first boot.
//
// Mount target is /mnt/perm-target — tmpfs, ephemeral, no collision
// with the installer's own /perm.
func writeFirstBootBundle(bundle *FirstBootBundle) error {
	const mountTarget = "/mnt/perm-target"
	if err := os.MkdirAll(mountTarget, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", mountTarget, err)
	}
	// Load ext4 module explicitly — in installer mode mountPerm() is skipped,
	// so ext4 is never loaded. Without -t ext4 busybox mount reads
	// /proc/filesystems, doesn't see ext4, and returns EINVAL.
	_ = exec.Command("/sbin/modprobe", "ext4").Run()

	// Use the kernel device-mapper path — kernel-created, no udev dependency.
	const metaDM = "/dev/mapper/capsule-meta"
	if out, err := exec.Command("/bin/mount", "-t", "ext4", metaDM, mountTarget).CombinedOutput(); err != nil {
		return fmt.Errorf("mount %s: %w: %s", metaDM, err, strings.TrimSpace(string(out)))
	}
	defer func() {
		_ = exec.Command("/bin/umount", mountTarget).Run()
	}()

	data, err := json.MarshalIndent(bundle, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal bundle: %w", err)
	}
	dst := filepath.Join(mountTarget, "firstboot.json")
	if err := os.WriteFile(dst, data, 0o600); err != nil {
		return fmt.Errorf("write %s: %w", dst, err)
	}
	// Also create the capsule subdir + tls subdir the disk-booted
	// capsule expects. mountPerm's ensurePermDirs does this on first
	// boot, but doing it here removes one race.
	for _, d := range []string{"capsule", "containerd", "containerd/root"} {
		_ = os.MkdirAll(filepath.Join(mountTarget, d), 0o755)
	}
	_ = os.MkdirAll(filepath.Join(mountTarget, "tls"), 0o700)
	// Force a sync so the bundle survives an immediate reboot.
	_ = exec.Command("/bin/sync").Run()
	return nil
}

// initTargetLVM runs the same first-boot LVM dance boot_linux.go does,
// but against the target disk's PERM partition. Naming the VG "capsule"
// matches what the disk's mountPerm expects on first boot.
//
// CAVEAT: LVM only allows one VG named "capsule" to be active at a
// time on the same machine. The installer's own USB also has VG
// "capsule" mounted at /perm (the in-memory store fallback covers the
// edge case where the USB's PERM is uninitialized). The pvcreate path
// here may surface a UUID warning; -ff -y forces past it.
// writeLVMLocalConf writes /etc/lvm/lvmlocal.conf to disable udev sync for
// the installer session. udev is not running in the installer boot env, so
// without this LVM activates LVs in device-mapper but skips creating
// /dev/<vg>/<lv> symlinks (those are normally handled by udev rules).
func writeLVMLocalConf() error {
	const conf = "activation {\n\tudev_sync = 0\n\tudev_rules = 0\n}\n"
	return os.WriteFile("/etc/lvm/lvmlocal.conf", []byte(conf), 0644)
}

func initTargetLVM(permDev string) error {
	if err := writeLVMLocalConf(); err != nil {
		return fmt.Errorf("lvm local conf: %w", err)
	}

	// Best-effort teardown of any leftover state from a previous failed install.
	_ = exec.Command("/sbin/vgchange", "-an", "capsule-target").Run()
	_ = exec.Command("/sbin/vgchange", "-an", "capsule").Run()
	_ = exec.Command("/sbin/vgremove", "-f", "-y", "capsule-target").Run()
	_ = exec.Command("/sbin/vgremove", "-f", "-y", "capsule").Run()
	_ = exec.Command("/sbin/pvremove", "-ff", "-y", permDev).Run()

	// Zero the first 16 MiB to destroy stale filesystem/LVM signatures.
	if out, err := exec.Command("/bin/dd",
		"if=/dev/zero", "of="+permDev, "bs=1M", "count=16", "conv=fsync",
	).CombinedOutput(); err != nil {
		return fmt.Errorf("zero %s: %w: %s", permDev, err, strings.TrimSpace(string(out)))
	}

	// Create VG directly as "capsule" — no rename needed because the installer
	// image has no PERM partition and therefore no competing "capsule" VG.
	for _, cmd := range [][]string{
		{"/sbin/pvcreate", "-ff", "-y", permDev},
		{"/sbin/vgcreate", "capsule", permDev},
		// Fixed 1 GiB meta LV; first runtime boot resizes as needed.
		{"/sbin/lvcreate", "-L", "1024M", "-n", "meta", "capsule"},
	} {
		if out, err := exec.Command(cmd[0], cmd[1:]...).CombinedOutput(); err != nil {
			return fmt.Errorf("%s: %w: %s", strings.Join(cmd, " "), err, strings.TrimSpace(string(out)))
		}
	}

	// Use the kernel device-mapper path (/dev/mapper/capsule-meta) for mkfs
	// — it is created directly by the kernel and doesn't depend on LVM
	// symlinks or udev. The LVM symlink (/dev/capsule/meta) may lag behind
	// depending on udev state.
	const metaDM = "/dev/mapper/capsule-meta"
	if out, err := exec.Command("/sbin/mkfs.ext4", "-q", "-F", "-L", "PERM", metaDM).CombinedOutput(); err != nil {
		return fmt.Errorf("mkfs.ext4 %s: %w: %s", metaDM, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// partitionPath returns the per-partition device path for a whole
// disk. Linux convention: SATA / USB disks get "/dev/sdaN"; NVMe gets
// "/dev/nvme0n1pN"; the "p" prefix is required when the disk name
// ends in a digit.
func partitionPath(disk string, n int) string {
	if disk == "" {
		return ""
	}
	last := disk[len(disk)-1]
	if last >= '0' && last <= '9' {
		return fmt.Sprintf("%sp%d", disk, n)
	}
	return fmt.Sprintf("%s%d", disk, n)
}

// rereadPartitions asks the kernel to re-scan the partition table.
// Equivalent to `partprobe` / `blockdev --rereadpt`. Required between
// WriteMBR and the per-partition writes; otherwise /dev/<disk>p1 etc.
// don't show up.
func rereadPartitions(disk string) error {
	out, err := exec.Command("/sbin/blockdev", "--rereadpt", disk).CombinedOutput()
	if err != nil {
		return fmt.Errorf("blockdev --rereadpt %s: %w: %s", disk, err, strings.TrimSpace(string(out)))
	}
	return nil
}

// waitForPath polls until path exists or deadline elapses. The kernel
// creates partition device nodes asynchronously after a BLKRRPART
// ioctl; without waiting, subsequent opens hit ENOENT.
func waitForPath(path string, deadline time.Duration) error {
	until := time.Now().Add(deadline)
	for time.Now().Before(until) {
		if _, err := os.Stat(path); err == nil {
			return nil
		}
		time.Sleep(50 * time.Millisecond)
	}
	return fmt.Errorf("%s not present after %s", path, deadline)
}

// copyProgress translates CopyPartition's byte-level callbacks into
// phase percentage updates suitable for InstallProgress.
func copyProgress(fn ProgressFn, phase string) func(done, total uint64) {
	return func(done, total uint64) {
		if total == 0 {
			fn(phase, 0, "")
			return
		}
		pct := uint32((done * 100) / total)
		if pct > 100 {
			pct = 100
		}
		fn(phase, pct, fmt.Sprintf("%d / %d MiB", done/(1024*1024), total/(1024*1024)))
	}
}

// patchBootGrubCfg mounts the target disk's FAT32 boot partition, seeds
// vmlinuz_b + initramfs_b from the installer's slot_a copies, and writes a
// runtime grub.cfg that references PARTUUID=b1a570ff (the runtime disk sig
// stamped by WriteMBR) instead of the installer's b005ab1e sig.
func patchBootGrubCfg(tgtBoot string) error {
	const mnt = "/mnt/boot-target"
	if err := os.MkdirAll(mnt, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", mnt, err)
	}
	if out, err := exec.Command("/bin/mount", "-t", "vfat", tgtBoot, mnt).CombinedOutput(); err != nil {
		return fmt.Errorf("mount %s: %w: %s", tgtBoot, err, strings.TrimSpace(string(out)))
	}
	defer func() { _ = exec.Command("/bin/umount", mnt).Run() }()

	// Installer boot partition only has vmlinuz_a + initramfs_a. Copy to b so
	// the runtime grub menu can reference both slots.
	for _, pair := range [][2]string{
		{"vmlinuz_a", "vmlinuz_b"},
		{"initramfs_a", "initramfs_b"},
	} {
		src := filepath.Join(mnt, pair[0])
		dst := filepath.Join(mnt, pair[1])
		if out, err := exec.Command("/bin/cp", src, dst).CombinedOutput(); err != nil {
			return fmt.Errorf("seed %s: %w: %s", pair[1], err, strings.TrimSpace(string(out)))
		}
	}

	// Runtime grub.cfg: A/B menu, timeout=2, correct PARTUUIDs for b1a570ff.
	const grubCfg = `set timeout=2
set default=0

menuentry "Capsule (slot_a)" {
    linux /vmlinuz_a root=PARTUUID=b1a570ff-02 rootfstype=squashfs ro random.trust_cpu=on capsule.slot=a console=tty0 console=ttyS0,115200n8 panic=10
    initrd /initramfs_a
}

menuentry "Capsule (slot_b)" {
    linux /vmlinuz_b root=PARTUUID=b1a570ff-03 rootfstype=squashfs ro random.trust_cpu=on capsule.slot=b console=tty0 console=ttyS0,115200n8 panic=10
    initrd /initramfs_b
}
`
	cfgPath := filepath.Join(mnt, "EFI", "BOOT", "grub.cfg")
	if err := os.WriteFile(cfgPath, []byte(grubCfg), 0o644); err != nil {
		return fmt.Errorf("write grub.cfg: %w", err)
	}
	_ = exec.Command("/bin/sync").Run()
	return nil
}

// fingerprintFromPEM parses a PEM cert blob and returns its SHA-256
// fingerprint, same shape as auth.FingerprintRaw output. Used to
// surface the future disk's TLS fingerprint in InstallResult.
func fingerprintFromPEM(certPEM string) (string, error) {
	block, _ := pem.Decode([]byte(certPEM))
	if block == nil || block.Type != "CERTIFICATE" {
		return "", fmt.Errorf("no CERTIFICATE block in PEM")
	}
	return auth.FingerprintRaw(block.Bytes), nil
}
