// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: capsule/v1/capsule.proto

package capsulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapsuleService_GetInfo_FullMethodName       = "/capsule.v1.CapsuleService/GetInfo"
	CapsuleService_StreamLogs_FullMethodName    = "/capsule.v1.CapsuleService/StreamLogs"
	CapsuleService_UpdateOS_FullMethodName      = "/capsule.v1.CapsuleService/UpdateOS"
	CapsuleService_UpdateConfirm_FullMethodName = "/capsule.v1.CapsuleService/UpdateConfirm"
)

// CapsuleServiceClient is the client API for CapsuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapsuleService exposes operations that describe or control the capsule
// (the running capsule instance on a single machine) as a whole.
type CapsuleServiceClient interface {
	// GetInfo returns identity and runtime information about this capsule.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// StreamLogs streams the capsuled daemon's own log output (slog).
	// This is the host-side log — boot, reconciler ticks, runtime driver
	// events. Separate from workload logs, which go via WorkloadService.Logs.
	StreamLogs(ctx context.Context, in *CapsuleLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CapsuleLogChunk], error)
	// UpdateOS streams a new OS update bundle from the operator to the
	// capsule. The first message is metadata (size + sha256); subsequent
	// messages carry chunked bytes. Capsuled writes the new rootfs to the
	// inactive A/B slot, copies the kernel + initramfs into /boot, sets a
	// syslinux one-shot for the next boot, persists pending state, and
	// schedules a reboot. The capsule comes back in TENTATIVE mode and
	// waits for UpdateConfirm — if that doesn't arrive before the deadline,
	// it auto-reboots and the bootloader's DEFAULT picks the prior slot.
	UpdateOS(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateOSRequest, UpdateOSResponse], error)
	// UpdateConfirm commits a tentative slot. Operator runs this after
	// they've verified the new slot is healthy. Rewrites the syslinux DEFAULT
	// and clears pending state.
	UpdateConfirm(ctx context.Context, in *UpdateConfirmRequest, opts ...grpc.CallOption) (*UpdateConfirmResponse, error)
}

type capsuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapsuleServiceClient(cc grpc.ClientConnInterface) CapsuleServiceClient {
	return &capsuleServiceClient{cc}
}

func (c *capsuleServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, CapsuleService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *capsuleServiceClient) StreamLogs(ctx context.Context, in *CapsuleLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CapsuleLogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CapsuleService_ServiceDesc.Streams[0], CapsuleService_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CapsuleLogsRequest, CapsuleLogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_StreamLogsClient = grpc.ServerStreamingClient[CapsuleLogChunk]

func (c *capsuleServiceClient) UpdateOS(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UpdateOSRequest, UpdateOSResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CapsuleService_ServiceDesc.Streams[1], CapsuleService_UpdateOS_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateOSRequest, UpdateOSResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_UpdateOSClient = grpc.ClientStreamingClient[UpdateOSRequest, UpdateOSResponse]

func (c *capsuleServiceClient) UpdateConfirm(ctx context.Context, in *UpdateConfirmRequest, opts ...grpc.CallOption) (*UpdateConfirmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfirmResponse)
	err := c.cc.Invoke(ctx, CapsuleService_UpdateConfirm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapsuleServiceServer is the server API for CapsuleService service.
// All implementations must embed UnimplementedCapsuleServiceServer
// for forward compatibility.
//
// CapsuleService exposes operations that describe or control the capsule
// (the running capsule instance on a single machine) as a whole.
type CapsuleServiceServer interface {
	// GetInfo returns identity and runtime information about this capsule.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// StreamLogs streams the capsuled daemon's own log output (slog).
	// This is the host-side log — boot, reconciler ticks, runtime driver
	// events. Separate from workload logs, which go via WorkloadService.Logs.
	StreamLogs(*CapsuleLogsRequest, grpc.ServerStreamingServer[CapsuleLogChunk]) error
	// UpdateOS streams a new OS update bundle from the operator to the
	// capsule. The first message is metadata (size + sha256); subsequent
	// messages carry chunked bytes. Capsuled writes the new rootfs to the
	// inactive A/B slot, copies the kernel + initramfs into /boot, sets a
	// syslinux one-shot for the next boot, persists pending state, and
	// schedules a reboot. The capsule comes back in TENTATIVE mode and
	// waits for UpdateConfirm — if that doesn't arrive before the deadline,
	// it auto-reboots and the bootloader's DEFAULT picks the prior slot.
	UpdateOS(grpc.ClientStreamingServer[UpdateOSRequest, UpdateOSResponse]) error
	// UpdateConfirm commits a tentative slot. Operator runs this after
	// they've verified the new slot is healthy. Rewrites the syslinux DEFAULT
	// and clears pending state.
	UpdateConfirm(context.Context, *UpdateConfirmRequest) (*UpdateConfirmResponse, error)
	mustEmbedUnimplementedCapsuleServiceServer()
}

// UnimplementedCapsuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapsuleServiceServer struct{}

func (UnimplementedCapsuleServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedCapsuleServiceServer) StreamLogs(*CapsuleLogsRequest, grpc.ServerStreamingServer[CapsuleLogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedCapsuleServiceServer) UpdateOS(grpc.ClientStreamingServer[UpdateOSRequest, UpdateOSResponse]) error {
	return status.Error(codes.Unimplemented, "method UpdateOS not implemented")
}
func (UnimplementedCapsuleServiceServer) UpdateConfirm(context.Context, *UpdateConfirmRequest) (*UpdateConfirmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfirm not implemented")
}
func (UnimplementedCapsuleServiceServer) mustEmbedUnimplementedCapsuleServiceServer() {}
func (UnimplementedCapsuleServiceServer) testEmbeddedByValue()                        {}

// UnsafeCapsuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapsuleServiceServer will
// result in compilation errors.
type UnsafeCapsuleServiceServer interface {
	mustEmbedUnimplementedCapsuleServiceServer()
}

func RegisterCapsuleServiceServer(s grpc.ServiceRegistrar, srv CapsuleServiceServer) {
	// If the following call panics, it indicates UnimplementedCapsuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapsuleService_ServiceDesc, srv)
}

func _CapsuleService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CapsuleService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CapsuleLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CapsuleServiceServer).StreamLogs(m, &grpc.GenericServerStream[CapsuleLogsRequest, CapsuleLogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_StreamLogsServer = grpc.ServerStreamingServer[CapsuleLogChunk]

func _CapsuleService_UpdateOS_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CapsuleServiceServer).UpdateOS(&grpc.GenericServerStream[UpdateOSRequest, UpdateOSResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CapsuleService_UpdateOSServer = grpc.ClientStreamingServer[UpdateOSRequest, UpdateOSResponse]

func _CapsuleService_UpdateConfirm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfirmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).UpdateConfirm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_UpdateConfirm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).UpdateConfirm(ctx, req.(*UpdateConfirmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapsuleService_ServiceDesc is the grpc.ServiceDesc for CapsuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapsuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capsule.v1.CapsuleService",
	HandlerType: (*CapsuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _CapsuleService_GetInfo_Handler,
		},
		{
			MethodName: "UpdateConfirm",
			Handler:    _CapsuleService_UpdateConfirm_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _CapsuleService_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateOS",
			Handler:       _CapsuleService_UpdateOS_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "capsule/v1/capsule.proto",
}
