// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: capsule/v1/capsule.proto

package capsulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapsuleService_GetInfo_FullMethodName = "/capsule.v1.CapsuleService/GetInfo"
)

// CapsuleServiceClient is the client API for CapsuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapsuleService exposes operations that describe or control the capsule
// (the running capsule instance on a single machine) as a whole.
type CapsuleServiceClient interface {
	// GetInfo returns identity and runtime information about this capsule.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
}

type capsuleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCapsuleServiceClient(cc grpc.ClientConnInterface) CapsuleServiceClient {
	return &capsuleServiceClient{cc}
}

func (c *capsuleServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, CapsuleService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapsuleServiceServer is the server API for CapsuleService service.
// All implementations must embed UnimplementedCapsuleServiceServer
// for forward compatibility.
//
// CapsuleService exposes operations that describe or control the capsule
// (the running capsule instance on a single machine) as a whole.
type CapsuleServiceServer interface {
	// GetInfo returns identity and runtime information about this capsule.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	mustEmbedUnimplementedCapsuleServiceServer()
}

// UnimplementedCapsuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapsuleServiceServer struct{}

func (UnimplementedCapsuleServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedCapsuleServiceServer) mustEmbedUnimplementedCapsuleServiceServer() {}
func (UnimplementedCapsuleServiceServer) testEmbeddedByValue()                        {}

// UnsafeCapsuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapsuleServiceServer will
// result in compilation errors.
type UnsafeCapsuleServiceServer interface {
	mustEmbedUnimplementedCapsuleServiceServer()
}

func RegisterCapsuleServiceServer(s grpc.ServiceRegistrar, srv CapsuleServiceServer) {
	// If the following call panics, it indicates UnimplementedCapsuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapsuleService_ServiceDesc, srv)
}

func _CapsuleService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapsuleServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapsuleService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapsuleServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapsuleService_ServiceDesc is the grpc.ServiceDesc for CapsuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapsuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capsule.v1.CapsuleService",
	HandlerType: (*CapsuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _CapsuleService_GetInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capsule/v1/capsule.proto",
}
