// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capsule/v1/capsule.proto

package capsulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname as reported by the kernel.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Kernel release string (uname -r).
	KernelRelease string `protobuf:"bytes,2,opt,name=kernel_release,json=kernelRelease,proto3" json:"kernel_release,omitempty"`
	// Kernel version string (uname -v).
	KernelVersion string `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// Machine architecture (uname -m).
	Architecture string `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// Seconds since boot.
	UptimeSeconds uint64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Capsule version baked into the binary at build time.
	CapsuleVersion string `protobuf:"bytes,6,opt,name=capsule_version,json=capsuleVersion,proto3" json:"capsule_version,omitempty"`
	// Which A/B slot is currently active. Empty string until A/B updates ship.
	ActiveSlot    string `protobuf:"bytes,7,opt,name=active_slot,json=activeSlot,proto3" json:"active_slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetInfoResponse) GetKernelRelease() string {
	if x != nil {
		return x.KernelRelease
	}
	return ""
}

func (x *GetInfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *GetInfoResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GetInfoResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetInfoResponse) GetCapsuleVersion() string {
	if x != nil {
		return x.CapsuleVersion
	}
	return ""
}

func (x *GetInfoResponse) GetActiveSlot() string {
	if x != nil {
		return x.ActiveSlot
	}
	return ""
}

var File_capsule_v1_capsule_proto protoreflect.FileDescriptor

const file_capsule_v1_capsule_proto_rawDesc = "" +
	"\n" +
	"\x18capsule/v1/capsule.proto\x12\n" +
	"capsule.v1\"\x10\n" +
	"\x0eGetInfoRequest\"\x90\x02\n" +
	"\x0fGetInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_release\x18\x02 \x01(\tR\rkernelRelease\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12'\n" +
	"\x0fcapsule_version\x18\x06 \x01(\tR\x0ecapsuleVersion\x12\x1f\n" +
	"\vactive_slot\x18\a \x01(\tR\n" +
	"activeSlot2T\n" +
	"\x0eCapsuleService\x12B\n" +
	"\aGetInfo\x12\x1a.capsule.v1.GetInfoRequest\x1a\x1b.capsule.v1.GetInfoResponseB\xa5\x01\n" +
	"\x0ecom.capsule.v1B\fCapsuleProtoP\x01Z<github.com/geekgonecrazy/capsule/models/capsule/v1;capsulev1\xa2\x02\x03CXX\xaa\x02\n" +
	"Capsule.V1\xca\x02\n" +
	"Capsule\\V1\xe2\x02\x16Capsule\\V1\\GPBMetadata\xea\x02\vCapsule::V1b\x06proto3"

var (
	file_capsule_v1_capsule_proto_rawDescOnce sync.Once
	file_capsule_v1_capsule_proto_rawDescData []byte
)

func file_capsule_v1_capsule_proto_rawDescGZIP() []byte {
	file_capsule_v1_capsule_proto_rawDescOnce.Do(func() {
		file_capsule_v1_capsule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capsule_v1_capsule_proto_rawDesc), len(file_capsule_v1_capsule_proto_rawDesc)))
	})
	return file_capsule_v1_capsule_proto_rawDescData
}

var file_capsule_v1_capsule_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_capsule_v1_capsule_proto_goTypes = []any{
	(*GetInfoRequest)(nil),  // 0: capsule.v1.GetInfoRequest
	(*GetInfoResponse)(nil), // 1: capsule.v1.GetInfoResponse
}
var file_capsule_v1_capsule_proto_depIdxs = []int32{
	0, // 0: capsule.v1.CapsuleService.GetInfo:input_type -> capsule.v1.GetInfoRequest
	1, // 1: capsule.v1.CapsuleService.GetInfo:output_type -> capsule.v1.GetInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_capsule_v1_capsule_proto_init() }
func file_capsule_v1_capsule_proto_init() {
	if File_capsule_v1_capsule_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capsule_v1_capsule_proto_rawDesc), len(file_capsule_v1_capsule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capsule_v1_capsule_proto_goTypes,
		DependencyIndexes: file_capsule_v1_capsule_proto_depIdxs,
		MessageInfos:      file_capsule_v1_capsule_proto_msgTypes,
	}.Build()
	File_capsule_v1_capsule_proto = out.File
	file_capsule_v1_capsule_proto_goTypes = nil
	file_capsule_v1_capsule_proto_depIdxs = nil
}
