// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capsule/v1/capsule.proto

package capsulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{0}
}

type GetInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hostname as reported by the kernel.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Kernel release string (uname -r).
	KernelRelease string `protobuf:"bytes,2,opt,name=kernel_release,json=kernelRelease,proto3" json:"kernel_release,omitempty"`
	// Kernel version string (uname -v).
	KernelVersion string `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	// Machine architecture (uname -m).
	Architecture string `protobuf:"bytes,4,opt,name=architecture,proto3" json:"architecture,omitempty"`
	// Seconds since boot.
	UptimeSeconds uint64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Capsule version baked into the binary at build time.
	CapsuleVersion string `protobuf:"bytes,6,opt,name=capsule_version,json=capsuleVersion,proto3" json:"capsule_version,omitempty"`
	// Which A/B slot booted this capsule ("slot_a" / "slot_b"). Empty in dev
	// mode (capsuled run off PID 1) or for old single-slot images.
	ActiveSlot string `protobuf:"bytes,7,opt,name=active_slot,json=activeSlot,proto3" json:"active_slot,omitempty"`
	// While an update is mid-commit, the slot we're trying. Empty otherwise.
	// If active_slot == pending_slot, we're in tentative mode and waiting
	// for UpdateConfirm before pending_deadline_unix.
	PendingSlot string `protobuf:"bytes,8,opt,name=pending_slot,json=pendingSlot,proto3" json:"pending_slot,omitempty"`
	// Unix timestamp (seconds) at which capsuled will auto-reboot to roll
	// back if no UpdateConfirm arrives. Zero when no update is pending.
	PendingDeadlineUnix int64 `protobuf:"varint,9,opt,name=pending_deadline_unix,json=pendingDeadlineUnix,proto3" json:"pending_deadline_unix,omitempty"`
	// VERSION string from the most recently committed (or pending) bundle.
	LastVersion string `protobuf:"bytes,10,opt,name=last_version,json=lastVersion,proto3" json:"last_version,omitempty"`
	// Total RAM (MemTotal from /proc/meminfo).
	MemoryTotalBytes uint64 `protobuf:"varint,11,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	// RAM currently available — sum of free + reclaimable caches
	// (MemAvailable from /proc/meminfo). What you'd actually be able to
	// allocate without hitting swap.
	MemoryAvailableBytes uint64 `protobuf:"varint,12,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
	// CPU logical core count.
	CpuCores uint32 `protobuf:"varint,13,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	// CPU model name from /proc/cpuinfo (first hit).
	CpuModel string `protobuf:"bytes,14,opt,name=cpu_model,json=cpuModel,proto3" json:"cpu_model,omitempty"`
	// Boot disk device path (e.g. "/dev/vda", "/dev/nvme0n1").
	BootDisk string `protobuf:"bytes,15,opt,name=boot_disk,json=bootDisk,proto3" json:"boot_disk,omitempty"`
	// Boot disk total size in bytes (BLKGETSIZE64).
	DiskTotalBytes uint64 `protobuf:"varint,16,opt,name=disk_total_bytes,json=diskTotalBytes,proto3" json:"disk_total_bytes,omitempty"`
	// LVM thin-pool data capacity. The thin pool backs every user volume,
	// so this is the practical "how much volume space the capsule has".
	ThinpoolTotalBytes uint64 `protobuf:"varint,17,opt,name=thinpool_total_bytes,json=thinpoolTotalBytes,proto3" json:"thinpool_total_bytes,omitempty"`
	// LVM thin-pool data currently allocated. Capsule fills up when this
	// approaches thinpool_total_bytes.
	ThinpoolUsedBytes uint64 `protobuf:"varint,18,opt,name=thinpool_used_bytes,json=thinpoolUsedBytes,proto3" json:"thinpool_used_bytes,omitempty"`
	// Capsule's current wall-clock time as Unix seconds. Lets capsulectl
	// surface clock skew between operator and capsule — drift breaks A/B
	// deadline-passed messages, log correlation, etc.
	LocalTimeUnix int64 `protobuf:"varint,19,opt,name=local_time_unix,json=localTimeUnix,proto3" json:"local_time_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetInfoResponse) GetKernelRelease() string {
	if x != nil {
		return x.KernelRelease
	}
	return ""
}

func (x *GetInfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *GetInfoResponse) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *GetInfoResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetInfoResponse) GetCapsuleVersion() string {
	if x != nil {
		return x.CapsuleVersion
	}
	return ""
}

func (x *GetInfoResponse) GetActiveSlot() string {
	if x != nil {
		return x.ActiveSlot
	}
	return ""
}

func (x *GetInfoResponse) GetPendingSlot() string {
	if x != nil {
		return x.PendingSlot
	}
	return ""
}

func (x *GetInfoResponse) GetPendingDeadlineUnix() int64 {
	if x != nil {
		return x.PendingDeadlineUnix
	}
	return 0
}

func (x *GetInfoResponse) GetLastVersion() string {
	if x != nil {
		return x.LastVersion
	}
	return ""
}

func (x *GetInfoResponse) GetMemoryTotalBytes() uint64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

func (x *GetInfoResponse) GetMemoryAvailableBytes() uint64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

func (x *GetInfoResponse) GetCpuCores() uint32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *GetInfoResponse) GetCpuModel() string {
	if x != nil {
		return x.CpuModel
	}
	return ""
}

func (x *GetInfoResponse) GetBootDisk() string {
	if x != nil {
		return x.BootDisk
	}
	return ""
}

func (x *GetInfoResponse) GetDiskTotalBytes() uint64 {
	if x != nil {
		return x.DiskTotalBytes
	}
	return 0
}

func (x *GetInfoResponse) GetThinpoolTotalBytes() uint64 {
	if x != nil {
		return x.ThinpoolTotalBytes
	}
	return 0
}

func (x *GetInfoResponse) GetThinpoolUsedBytes() uint64 {
	if x != nil {
		return x.ThinpoolUsedBytes
	}
	return 0
}

func (x *GetInfoResponse) GetLocalTimeUnix() int64 {
	if x != nil {
		return x.LocalTimeUnix
	}
	return 0
}

type CapsuleLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, keep the stream open and emit new log lines as they arrive.
	Follow bool `protobuf:"varint,1,opt,name=follow,proto3" json:"follow,omitempty"`
	// Return only the last N lines from the existing log before streaming.
	// 0 = from the start of the file.
	TailLines     int32 `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapsuleLogsRequest) Reset() {
	*x = CapsuleLogsRequest{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsuleLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleLogsRequest) ProtoMessage() {}

func (x *CapsuleLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleLogsRequest.ProtoReflect.Descriptor instead.
func (*CapsuleLogsRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{2}
}

func (x *CapsuleLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *CapsuleLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type CapsuleLogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw log bytes. Line framing is preserved but not guaranteed.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapsuleLogChunk) Reset() {
	*x = CapsuleLogChunk{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapsuleLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapsuleLogChunk) ProtoMessage() {}

func (x *CapsuleLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapsuleLogChunk.ProtoReflect.Descriptor instead.
func (*CapsuleLogChunk) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{3}
}

func (x *CapsuleLogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateOSRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*UpdateOSRequest_Metadata
	//	*UpdateOSRequest_Chunk
	Msg           isUpdateOSRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOSRequest) Reset() {
	*x = UpdateOSRequest{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOSRequest) ProtoMessage() {}

func (x *UpdateOSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOSRequest.ProtoReflect.Descriptor instead.
func (*UpdateOSRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateOSRequest) GetMsg() isUpdateOSRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *UpdateOSRequest) GetMetadata() *UpdateOSMetadata {
	if x != nil {
		if x, ok := x.Msg.(*UpdateOSRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UpdateOSRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Msg.(*UpdateOSRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUpdateOSRequest_Msg interface {
	isUpdateOSRequest_Msg()
}

type UpdateOSRequest_Metadata struct {
	Metadata *UpdateOSMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // first message only
}

type UpdateOSRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // subsequent streaming bytes (1 MiB recommended)
}

func (*UpdateOSRequest_Metadata) isUpdateOSRequest_Msg() {}

func (*UpdateOSRequest_Chunk) isUpdateOSRequest_Msg() {}

type UpdateOSMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total bundle size in bytes.
	TotalBytes uint64 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// sha256 of the whole bundle, lowercase hex. Server verifies before apply.
	Sha256Hex     string `protobuf:"bytes,2,opt,name=sha256_hex,json=sha256Hex,proto3" json:"sha256_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOSMetadata) Reset() {
	*x = UpdateOSMetadata{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOSMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOSMetadata) ProtoMessage() {}

func (x *UpdateOSMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOSMetadata.ProtoReflect.Descriptor instead.
func (*UpdateOSMetadata) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateOSMetadata) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *UpdateOSMetadata) GetSha256Hex() string {
	if x != nil {
		return x.Sha256Hex
	}
	return ""
}

type UpdateOSResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slot the bundle was written to ("slot_a" / "slot_b").
	NextSlot string `protobuf:"bytes,1,opt,name=next_slot,json=nextSlot,proto3" json:"next_slot,omitempty"`
	// VERSION string from the bundle.
	NextVersion string `protobuf:"bytes,2,opt,name=next_version,json=nextVersion,proto3" json:"next_version,omitempty"`
	// Always true on success today; reserved for future "stage but don't reboot" flows.
	RebootScheduled bool `protobuf:"varint,3,opt,name=reboot_scheduled,json=rebootScheduled,proto3" json:"reboot_scheduled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateOSResponse) Reset() {
	*x = UpdateOSResponse{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOSResponse) ProtoMessage() {}

func (x *UpdateOSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOSResponse.ProtoReflect.Descriptor instead.
func (*UpdateOSResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateOSResponse) GetNextSlot() string {
	if x != nil {
		return x.NextSlot
	}
	return ""
}

func (x *UpdateOSResponse) GetNextVersion() string {
	if x != nil {
		return x.NextVersion
	}
	return ""
}

func (x *UpdateOSResponse) GetRebootScheduled() bool {
	if x != nil {
		return x.RebootScheduled
	}
	return false
}

type UpdateConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfirmRequest) Reset() {
	*x = UpdateConfirmRequest{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfirmRequest) ProtoMessage() {}

func (x *UpdateConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfirmRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfirmRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{7}
}

type UpdateConfirmResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slot that was committed.
	CommittedSlot string `protobuf:"bytes,1,opt,name=committed_slot,json=committedSlot,proto3" json:"committed_slot,omitempty"`
	// VERSION committed.
	CommittedVersion string `protobuf:"bytes,2,opt,name=committed_version,json=committedVersion,proto3" json:"committed_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateConfirmResponse) Reset() {
	*x = UpdateConfirmResponse{}
	mi := &file_capsule_v1_capsule_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfirmResponse) ProtoMessage() {}

func (x *UpdateConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_capsule_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfirmResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfirmResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_capsule_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateConfirmResponse) GetCommittedSlot() string {
	if x != nil {
		return x.CommittedSlot
	}
	return ""
}

func (x *UpdateConfirmResponse) GetCommittedVersion() string {
	if x != nil {
		return x.CommittedVersion
	}
	return ""
}

var File_capsule_v1_capsule_proto protoreflect.FileDescriptor

const file_capsule_v1_capsule_proto_rawDesc = "" +
	"\n" +
	"\x18capsule/v1/capsule.proto\x12\n" +
	"capsule.v1\"\x10\n" +
	"\x0eGetInfoRequest\"\xf9\x05\n" +
	"\x0fGetInfoResponse\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_release\x18\x02 \x01(\tR\rkernelRelease\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12\"\n" +
	"\farchitecture\x18\x04 \x01(\tR\farchitecture\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12'\n" +
	"\x0fcapsule_version\x18\x06 \x01(\tR\x0ecapsuleVersion\x12\x1f\n" +
	"\vactive_slot\x18\a \x01(\tR\n" +
	"activeSlot\x12!\n" +
	"\fpending_slot\x18\b \x01(\tR\vpendingSlot\x122\n" +
	"\x15pending_deadline_unix\x18\t \x01(\x03R\x13pendingDeadlineUnix\x12!\n" +
	"\flast_version\x18\n" +
	" \x01(\tR\vlastVersion\x12,\n" +
	"\x12memory_total_bytes\x18\v \x01(\x04R\x10memoryTotalBytes\x124\n" +
	"\x16memory_available_bytes\x18\f \x01(\x04R\x14memoryAvailableBytes\x12\x1b\n" +
	"\tcpu_cores\x18\r \x01(\rR\bcpuCores\x12\x1b\n" +
	"\tcpu_model\x18\x0e \x01(\tR\bcpuModel\x12\x1b\n" +
	"\tboot_disk\x18\x0f \x01(\tR\bbootDisk\x12(\n" +
	"\x10disk_total_bytes\x18\x10 \x01(\x04R\x0ediskTotalBytes\x120\n" +
	"\x14thinpool_total_bytes\x18\x11 \x01(\x04R\x12thinpoolTotalBytes\x12.\n" +
	"\x13thinpool_used_bytes\x18\x12 \x01(\x04R\x11thinpoolUsedBytes\x12&\n" +
	"\x0flocal_time_unix\x18\x13 \x01(\x03R\rlocalTimeUnix\"K\n" +
	"\x12CapsuleLogsRequest\x12\x16\n" +
	"\x06follow\x18\x01 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\"%\n" +
	"\x0fCapsuleLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"l\n" +
	"\x0fUpdateOSRequest\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1c.capsule.v1.UpdateOSMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x05\n" +
	"\x03msg\"R\n" +
	"\x10UpdateOSMetadata\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\x12\x1d\n" +
	"\n" +
	"sha256_hex\x18\x02 \x01(\tR\tsha256Hex\"}\n" +
	"\x10UpdateOSResponse\x12\x1b\n" +
	"\tnext_slot\x18\x01 \x01(\tR\bnextSlot\x12!\n" +
	"\fnext_version\x18\x02 \x01(\tR\vnextVersion\x12)\n" +
	"\x10reboot_scheduled\x18\x03 \x01(\bR\x0frebootScheduled\"\x16\n" +
	"\x14UpdateConfirmRequest\"k\n" +
	"\x15UpdateConfirmResponse\x12%\n" +
	"\x0ecommitted_slot\x18\x01 \x01(\tR\rcommittedSlot\x12+\n" +
	"\x11committed_version\x18\x02 \x01(\tR\x10committedVersion2\xc0\x02\n" +
	"\x0eCapsuleService\x12B\n" +
	"\aGetInfo\x12\x1a.capsule.v1.GetInfoRequest\x1a\x1b.capsule.v1.GetInfoResponse\x12K\n" +
	"\n" +
	"StreamLogs\x12\x1e.capsule.v1.CapsuleLogsRequest\x1a\x1b.capsule.v1.CapsuleLogChunk0\x01\x12G\n" +
	"\bUpdateOS\x12\x1b.capsule.v1.UpdateOSRequest\x1a\x1c.capsule.v1.UpdateOSResponse(\x01\x12T\n" +
	"\rUpdateConfirm\x12 .capsule.v1.UpdateConfirmRequest\x1a!.capsule.v1.UpdateConfirmResponseB\xa5\x01\n" +
	"\x0ecom.capsule.v1B\fCapsuleProtoP\x01Z<github.com/geekgonecrazy/capsule/models/capsule/v1;capsulev1\xa2\x02\x03CXX\xaa\x02\n" +
	"Capsule.V1\xca\x02\n" +
	"Capsule\\V1\xe2\x02\x16Capsule\\V1\\GPBMetadata\xea\x02\vCapsule::V1b\x06proto3"

var (
	file_capsule_v1_capsule_proto_rawDescOnce sync.Once
	file_capsule_v1_capsule_proto_rawDescData []byte
)

func file_capsule_v1_capsule_proto_rawDescGZIP() []byte {
	file_capsule_v1_capsule_proto_rawDescOnce.Do(func() {
		file_capsule_v1_capsule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capsule_v1_capsule_proto_rawDesc), len(file_capsule_v1_capsule_proto_rawDesc)))
	})
	return file_capsule_v1_capsule_proto_rawDescData
}

var file_capsule_v1_capsule_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_capsule_v1_capsule_proto_goTypes = []any{
	(*GetInfoRequest)(nil),        // 0: capsule.v1.GetInfoRequest
	(*GetInfoResponse)(nil),       // 1: capsule.v1.GetInfoResponse
	(*CapsuleLogsRequest)(nil),    // 2: capsule.v1.CapsuleLogsRequest
	(*CapsuleLogChunk)(nil),       // 3: capsule.v1.CapsuleLogChunk
	(*UpdateOSRequest)(nil),       // 4: capsule.v1.UpdateOSRequest
	(*UpdateOSMetadata)(nil),      // 5: capsule.v1.UpdateOSMetadata
	(*UpdateOSResponse)(nil),      // 6: capsule.v1.UpdateOSResponse
	(*UpdateConfirmRequest)(nil),  // 7: capsule.v1.UpdateConfirmRequest
	(*UpdateConfirmResponse)(nil), // 8: capsule.v1.UpdateConfirmResponse
}
var file_capsule_v1_capsule_proto_depIdxs = []int32{
	5, // 0: capsule.v1.UpdateOSRequest.metadata:type_name -> capsule.v1.UpdateOSMetadata
	0, // 1: capsule.v1.CapsuleService.GetInfo:input_type -> capsule.v1.GetInfoRequest
	2, // 2: capsule.v1.CapsuleService.StreamLogs:input_type -> capsule.v1.CapsuleLogsRequest
	4, // 3: capsule.v1.CapsuleService.UpdateOS:input_type -> capsule.v1.UpdateOSRequest
	7, // 4: capsule.v1.CapsuleService.UpdateConfirm:input_type -> capsule.v1.UpdateConfirmRequest
	1, // 5: capsule.v1.CapsuleService.GetInfo:output_type -> capsule.v1.GetInfoResponse
	3, // 6: capsule.v1.CapsuleService.StreamLogs:output_type -> capsule.v1.CapsuleLogChunk
	6, // 7: capsule.v1.CapsuleService.UpdateOS:output_type -> capsule.v1.UpdateOSResponse
	8, // 8: capsule.v1.CapsuleService.UpdateConfirm:output_type -> capsule.v1.UpdateConfirmResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_capsule_v1_capsule_proto_init() }
func file_capsule_v1_capsule_proto_init() {
	if File_capsule_v1_capsule_proto != nil {
		return
	}
	file_capsule_v1_capsule_proto_msgTypes[4].OneofWrappers = []any{
		(*UpdateOSRequest_Metadata)(nil),
		(*UpdateOSRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capsule_v1_capsule_proto_rawDesc), len(file_capsule_v1_capsule_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capsule_v1_capsule_proto_goTypes,
		DependencyIndexes: file_capsule_v1_capsule_proto_depIdxs,
		MessageInfos:      file_capsule_v1_capsule_proto_msgTypes,
	}.Build()
	File_capsule_v1_capsule_proto = out.File
	file_capsule_v1_capsule_proto_goTypes = nil
	file_capsule_v1_capsule_proto_depIdxs = nil
}
