// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capsule/v1/guest.proto

package capsulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadPhase int32

const (
	PayloadPhase_PAYLOAD_PHASE_UNSPECIFIED PayloadPhase = 0
	PayloadPhase_PAYLOAD_PHASE_RUNNING     PayloadPhase = 1
	PayloadPhase_PAYLOAD_PHASE_EXITED      PayloadPhase = 2
	PayloadPhase_PAYLOAD_PHASE_FAILED      PayloadPhase = 3
)

// Enum value maps for PayloadPhase.
var (
	PayloadPhase_name = map[int32]string{
		0: "PAYLOAD_PHASE_UNSPECIFIED",
		1: "PAYLOAD_PHASE_RUNNING",
		2: "PAYLOAD_PHASE_EXITED",
		3: "PAYLOAD_PHASE_FAILED",
	}
	PayloadPhase_value = map[string]int32{
		"PAYLOAD_PHASE_UNSPECIFIED": 0,
		"PAYLOAD_PHASE_RUNNING":     1,
		"PAYLOAD_PHASE_EXITED":      2,
		"PAYLOAD_PHASE_FAILED":      3,
	}
)

func (x PayloadPhase) Enum() *PayloadPhase {
	p := new(PayloadPhase)
	*p = x
	return p
}

func (x PayloadPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_capsule_v1_guest_proto_enumTypes[0].Descriptor()
}

func (PayloadPhase) Type() protoreflect.EnumType {
	return &file_capsule_v1_guest_proto_enumTypes[0]
}

func (x PayloadPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PayloadPhase.Descriptor instead.
func (PayloadPhase) EnumDescriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_capsule_v1_guest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Agent build version baked into capsule-guest.
	AgentVersion string `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Seconds since the VM booted (guest uptime).
	UptimeSeconds uint64 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_capsule_v1_guest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *PingResponse) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type StartPayloadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block device inside the VM that holds the payload rootfs (ext4).
	// Almost always "/dev/vdb" in Capsule's layout.
	PayloadBlockDevice string `protobuf:"bytes,1,opt,name=payload_block_device,json=payloadBlockDevice,proto3" json:"payload_block_device,omitempty"`
	// Command / entrypoint to run (argv). Required.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// Environment vars to set, in NAME=VALUE form.
	Env []string `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	// Working directory inside the payload rootfs. Empty means "/".
	WorkingDir string `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	// If true, the payload runs in a chroot into the mounted rootfs.
	// If false, the agent just execs directly (used for escape-hatch
	// debugging against the shared rootfs itself).
	Chroot bool `protobuf:"varint,5,opt,name=chroot,proto3" json:"chroot,omitempty"`
	// Additional block devices (volumes) to mount inside the payload rootfs.
	// Each entry is mounted at mount_path (relative to the payload rootfs).
	Mounts        []*GuestVolumeMount `protobuf:"bytes,6,rep,name=mounts,proto3" json:"mounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPayloadRequest) Reset() {
	*x = StartPayloadRequest{}
	mi := &file_capsule_v1_guest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPayloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPayloadRequest) ProtoMessage() {}

func (x *StartPayloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPayloadRequest.ProtoReflect.Descriptor instead.
func (*StartPayloadRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{2}
}

func (x *StartPayloadRequest) GetPayloadBlockDevice() string {
	if x != nil {
		return x.PayloadBlockDevice
	}
	return ""
}

func (x *StartPayloadRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *StartPayloadRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *StartPayloadRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *StartPayloadRequest) GetChroot() bool {
	if x != nil {
		return x.Chroot
	}
	return false
}

func (x *StartPayloadRequest) GetMounts() []*GuestVolumeMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

type GuestVolumeMount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Block device inside the VM, e.g. "/dev/vdc".
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// Mount path inside the payload rootfs, e.g. "/data".
	MountPath string `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	// Filesystem type. Defaults to "ext4".
	Fstype string `protobuf:"bytes,3,opt,name=fstype,proto3" json:"fstype,omitempty"`
	// If true, mount read-only.
	ReadOnly      bool `protobuf:"varint,4,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuestVolumeMount) Reset() {
	*x = GuestVolumeMount{}
	mi := &file_capsule_v1_guest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuestVolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuestVolumeMount) ProtoMessage() {}

func (x *GuestVolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuestVolumeMount.ProtoReflect.Descriptor instead.
func (*GuestVolumeMount) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{3}
}

func (x *GuestVolumeMount) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *GuestVolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *GuestVolumeMount) GetFstype() string {
	if x != nil {
		return x.Fstype
	}
	return ""
}

func (x *GuestVolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type StartPayloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayloadPid    int32                  `protobuf:"varint,1,opt,name=payload_pid,json=payloadPid,proto3" json:"payload_pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPayloadResponse) Reset() {
	*x = StartPayloadResponse{}
	mi := &file_capsule_v1_guest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPayloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPayloadResponse) ProtoMessage() {}

func (x *StartPayloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPayloadResponse.ProtoReflect.Descriptor instead.
func (*StartPayloadResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{4}
}

func (x *StartPayloadResponse) GetPayloadPid() int32 {
	if x != nil {
		return x.PayloadPid
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_capsule_v1_guest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{5}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         PayloadPhase           `protobuf:"varint,1,opt,name=phase,proto3,enum=capsule.v1.PayloadPhase" json:"phase,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_capsule_v1_guest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetPhase() PayloadPhase {
	if x != nil {
		return x.Phase
	}
	return PayloadPhase_PAYLOAD_PHASE_UNSPECIFIED
}

func (x *StatusResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Follow        bool                   `protobuf:"varint,1,opt,name=follow,proto3" json:"follow,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsRequest) Reset() {
	*x = LogsRequest{}
	mi := &file_capsule_v1_guest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsRequest) ProtoMessage() {}

func (x *LogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsRequest.ProtoReflect.Descriptor instead.
func (*LogsRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{7}
}

func (x *LogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *LogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_capsule_v1_guest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{8}
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecClientMessage_Config
	//	*ExecClientMessage_Stdin
	//	*ExecClientMessage_Resize
	Payload       isExecClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecClientMessage) Reset() {
	*x = ExecClientMessage{}
	mi := &file_capsule_v1_guest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecClientMessage) ProtoMessage() {}

func (x *ExecClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecClientMessage.ProtoReflect.Descriptor instead.
func (*ExecClientMessage) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{9}
}

func (x *ExecClientMessage) GetPayload() isExecClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecClientMessage) GetConfig() *ExecConfig {
	if x != nil {
		if x, ok := x.Payload.(*ExecClientMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *ExecClientMessage) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecClientMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecClientMessage) GetResize() *ExecResize {
	if x != nil {
		if x, ok := x.Payload.(*ExecClientMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecClientMessage_Payload interface {
	isExecClientMessage_Payload()
}

type ExecClientMessage_Config struct {
	Config *ExecConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type ExecClientMessage_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecClientMessage_Resize struct {
	Resize *ExecResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*ExecClientMessage_Config) isExecClientMessage_Payload() {}

func (*ExecClientMessage_Stdin) isExecClientMessage_Payload() {}

func (*ExecClientMessage_Resize) isExecClientMessage_Payload() {}

type ExecConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []string               `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Tty           bool                   `protobuf:"varint,2,opt,name=tty,proto3" json:"tty,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecConfig) Reset() {
	*x = ExecConfig{}
	mi := &file_capsule_v1_guest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecConfig) ProtoMessage() {}

func (x *ExecConfig) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecConfig.ProtoReflect.Descriptor instead.
func (*ExecConfig) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{10}
}

func (x *ExecConfig) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ExecConfig) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type ExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResize) Reset() {
	*x = ExecResize{}
	mi := &file_capsule_v1_guest_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResize) ProtoMessage() {}

func (x *ExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResize.ProtoReflect.Descriptor instead.
func (*ExecResize) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{11}
}

func (x *ExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ExecServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ExecServerMessage_Stdout
	//	*ExecServerMessage_Stderr
	//	*ExecServerMessage_Exit
	Payload       isExecServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecServerMessage) Reset() {
	*x = ExecServerMessage{}
	mi := &file_capsule_v1_guest_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecServerMessage) ProtoMessage() {}

func (x *ExecServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecServerMessage.ProtoReflect.Descriptor instead.
func (*ExecServerMessage) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{12}
}

func (x *ExecServerMessage) GetPayload() isExecServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecServerMessage) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecServerMessage_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecServerMessage) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*ExecServerMessage_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecServerMessage) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Payload.(*ExecServerMessage_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecServerMessage_Payload interface {
	isExecServerMessage_Payload()
}

type ExecServerMessage_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecServerMessage_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecServerMessage_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecServerMessage_Stdout) isExecServerMessage_Payload() {}

func (*ExecServerMessage_Stderr) isExecServerMessage_Payload() {}

func (*ExecServerMessage_Exit) isExecServerMessage_Payload() {}

type ExecExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_capsule_v1_guest_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{13}
}

func (x *ExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GraceSeconds  uint32                 `protobuf:"varint,1,opt,name=grace_seconds,json=graceSeconds,proto3" json:"grace_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_capsule_v1_guest_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{14}
}

func (x *StopRequest) GetGraceSeconds() uint32 {
	if x != nil {
		return x.GraceSeconds
	}
	return 0
}

type StopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopResponse) Reset() {
	*x = StopResponse{}
	mi := &file_capsule_v1_guest_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopResponse) ProtoMessage() {}

func (x *StopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_guest_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopResponse.ProtoReflect.Descriptor instead.
func (*StopResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_guest_proto_rawDescGZIP(), []int{15}
}

var File_capsule_v1_guest_proto protoreflect.FileDescriptor

const file_capsule_v1_guest_proto_rawDesc = "" +
	"\n" +
	"\x16capsule/v1/guest.proto\x12\n" +
	"capsule.v1\"\r\n" +
	"\vPingRequest\"Z\n" +
	"\fPingResponse\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x04R\ruptimeSeconds\"\xe2\x01\n" +
	"\x13StartPayloadRequest\x120\n" +
	"\x14payload_block_device\x18\x01 \x01(\tR\x12payloadBlockDevice\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03env\x18\x03 \x03(\tR\x03env\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12\x16\n" +
	"\x06chroot\x18\x05 \x01(\bR\x06chroot\x124\n" +
	"\x06mounts\x18\x06 \x03(\v2\x1c.capsule.v1.GuestVolumeMountR\x06mounts\"~\n" +
	"\x10GuestVolumeMount\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x16\n" +
	"\x06fstype\x18\x03 \x01(\tR\x06fstype\x12\x1b\n" +
	"\tread_only\x18\x04 \x01(\bR\breadOnly\"7\n" +
	"\x14StartPayloadResponse\x12\x1f\n" +
	"\vpayload_pid\x18\x01 \x01(\x05R\n" +
	"payloadPid\"\x0f\n" +
	"\rStatusRequest\"w\n" +
	"\x0eStatusResponse\x12.\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x18.capsule.v1.PayloadPhaseR\x05phase\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"D\n" +
	"\vLogsRequest\x12\x16\n" +
	"\x06follow\x18\x01 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\"\x1e\n" +
	"\bLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x9a\x01\n" +
	"\x11ExecClientMessage\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x16.capsule.v1.ExecConfigH\x00R\x06config\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x120\n" +
	"\x06resize\x18\x03 \x01(\v2\x16.capsule.v1.ExecResizeH\x00R\x06resizeB\t\n" +
	"\apayload\"\xa3\x01\n" +
	"\n" +
	"ExecConfig\x12\x18\n" +
	"\acommand\x18\x01 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x02 \x01(\bR\x03tty\x121\n" +
	"\x03env\x18\x03 \x03(\v2\x1f.capsule.v1.ExecConfig.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\n" +
	"ExecResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"~\n" +
	"\x11ExecServerMessage\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12*\n" +
	"\x04exit\x18\x03 \x01(\v2\x14.capsule.v1.ExecExitH\x00R\x04exitB\t\n" +
	"\apayload\"'\n" +
	"\bExecExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\"2\n" +
	"\vStopRequest\x12#\n" +
	"\rgrace_seconds\x18\x01 \x01(\rR\fgraceSeconds\"\x0e\n" +
	"\fStopResponse*|\n" +
	"\fPayloadPhase\x12\x1d\n" +
	"\x19PAYLOAD_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYLOAD_PHASE_RUNNING\x10\x01\x12\x18\n" +
	"\x14PAYLOAD_PHASE_EXITED\x10\x02\x12\x18\n" +
	"\x14PAYLOAD_PHASE_FAILED\x10\x032\x99\x03\n" +
	"\n" +
	"GuestAgent\x129\n" +
	"\x04Ping\x12\x17.capsule.v1.PingRequest\x1a\x18.capsule.v1.PingResponse\x12Q\n" +
	"\fStartPayload\x12\x1f.capsule.v1.StartPayloadRequest\x1a .capsule.v1.StartPayloadResponse\x12?\n" +
	"\x06Status\x12\x19.capsule.v1.StatusRequest\x1a\x1a.capsule.v1.StatusResponse\x127\n" +
	"\x04Logs\x12\x17.capsule.v1.LogsRequest\x1a\x14.capsule.v1.LogChunk0\x01\x12H\n" +
	"\x04Exec\x12\x1d.capsule.v1.ExecClientMessage\x1a\x1d.capsule.v1.ExecServerMessage(\x010\x01\x129\n" +
	"\x04Stop\x12\x17.capsule.v1.StopRequest\x1a\x18.capsule.v1.StopResponseB\xa3\x01\n" +
	"\x0ecom.capsule.v1B\n" +
	"GuestProtoP\x01Z<github.com/geekgonecrazy/capsule/models/capsule/v1;capsulev1\xa2\x02\x03CXX\xaa\x02\n" +
	"Capsule.V1\xca\x02\n" +
	"Capsule\\V1\xe2\x02\x16Capsule\\V1\\GPBMetadata\xea\x02\vCapsule::V1b\x06proto3"

var (
	file_capsule_v1_guest_proto_rawDescOnce sync.Once
	file_capsule_v1_guest_proto_rawDescData []byte
)

func file_capsule_v1_guest_proto_rawDescGZIP() []byte {
	file_capsule_v1_guest_proto_rawDescOnce.Do(func() {
		file_capsule_v1_guest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capsule_v1_guest_proto_rawDesc), len(file_capsule_v1_guest_proto_rawDesc)))
	})
	return file_capsule_v1_guest_proto_rawDescData
}

var file_capsule_v1_guest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_capsule_v1_guest_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_capsule_v1_guest_proto_goTypes = []any{
	(PayloadPhase)(0),            // 0: capsule.v1.PayloadPhase
	(*PingRequest)(nil),          // 1: capsule.v1.PingRequest
	(*PingResponse)(nil),         // 2: capsule.v1.PingResponse
	(*StartPayloadRequest)(nil),  // 3: capsule.v1.StartPayloadRequest
	(*GuestVolumeMount)(nil),     // 4: capsule.v1.GuestVolumeMount
	(*StartPayloadResponse)(nil), // 5: capsule.v1.StartPayloadResponse
	(*StatusRequest)(nil),        // 6: capsule.v1.StatusRequest
	(*StatusResponse)(nil),       // 7: capsule.v1.StatusResponse
	(*LogsRequest)(nil),          // 8: capsule.v1.LogsRequest
	(*LogChunk)(nil),             // 9: capsule.v1.LogChunk
	(*ExecClientMessage)(nil),    // 10: capsule.v1.ExecClientMessage
	(*ExecConfig)(nil),           // 11: capsule.v1.ExecConfig
	(*ExecResize)(nil),           // 12: capsule.v1.ExecResize
	(*ExecServerMessage)(nil),    // 13: capsule.v1.ExecServerMessage
	(*ExecExit)(nil),             // 14: capsule.v1.ExecExit
	(*StopRequest)(nil),          // 15: capsule.v1.StopRequest
	(*StopResponse)(nil),         // 16: capsule.v1.StopResponse
	nil,                          // 17: capsule.v1.ExecConfig.EnvEntry
}
var file_capsule_v1_guest_proto_depIdxs = []int32{
	4,  // 0: capsule.v1.StartPayloadRequest.mounts:type_name -> capsule.v1.GuestVolumeMount
	0,  // 1: capsule.v1.StatusResponse.phase:type_name -> capsule.v1.PayloadPhase
	11, // 2: capsule.v1.ExecClientMessage.config:type_name -> capsule.v1.ExecConfig
	12, // 3: capsule.v1.ExecClientMessage.resize:type_name -> capsule.v1.ExecResize
	17, // 4: capsule.v1.ExecConfig.env:type_name -> capsule.v1.ExecConfig.EnvEntry
	14, // 5: capsule.v1.ExecServerMessage.exit:type_name -> capsule.v1.ExecExit
	1,  // 6: capsule.v1.GuestAgent.Ping:input_type -> capsule.v1.PingRequest
	3,  // 7: capsule.v1.GuestAgent.StartPayload:input_type -> capsule.v1.StartPayloadRequest
	6,  // 8: capsule.v1.GuestAgent.Status:input_type -> capsule.v1.StatusRequest
	8,  // 9: capsule.v1.GuestAgent.Logs:input_type -> capsule.v1.LogsRequest
	10, // 10: capsule.v1.GuestAgent.Exec:input_type -> capsule.v1.ExecClientMessage
	15, // 11: capsule.v1.GuestAgent.Stop:input_type -> capsule.v1.StopRequest
	2,  // 12: capsule.v1.GuestAgent.Ping:output_type -> capsule.v1.PingResponse
	5,  // 13: capsule.v1.GuestAgent.StartPayload:output_type -> capsule.v1.StartPayloadResponse
	7,  // 14: capsule.v1.GuestAgent.Status:output_type -> capsule.v1.StatusResponse
	9,  // 15: capsule.v1.GuestAgent.Logs:output_type -> capsule.v1.LogChunk
	13, // 16: capsule.v1.GuestAgent.Exec:output_type -> capsule.v1.ExecServerMessage
	16, // 17: capsule.v1.GuestAgent.Stop:output_type -> capsule.v1.StopResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_capsule_v1_guest_proto_init() }
func file_capsule_v1_guest_proto_init() {
	if File_capsule_v1_guest_proto != nil {
		return
	}
	file_capsule_v1_guest_proto_msgTypes[9].OneofWrappers = []any{
		(*ExecClientMessage_Config)(nil),
		(*ExecClientMessage_Stdin)(nil),
		(*ExecClientMessage_Resize)(nil),
	}
	file_capsule_v1_guest_proto_msgTypes[12].OneofWrappers = []any{
		(*ExecServerMessage_Stdout)(nil),
		(*ExecServerMessage_Stderr)(nil),
		(*ExecServerMessage_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capsule_v1_guest_proto_rawDesc), len(file_capsule_v1_guest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capsule_v1_guest_proto_goTypes,
		DependencyIndexes: file_capsule_v1_guest_proto_depIdxs,
		EnumInfos:         file_capsule_v1_guest_proto_enumTypes,
		MessageInfos:      file_capsule_v1_guest_proto_msgTypes,
	}.Build()
	File_capsule_v1_guest_proto = out.File
	file_capsule_v1_guest_proto_goTypes = nil
	file_capsule_v1_guest_proto_depIdxs = nil
}
