// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: capsule/v1/guest.proto

package capsulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GuestAgent_Ping_FullMethodName         = "/capsule.v1.GuestAgent/Ping"
	GuestAgent_StartPayload_FullMethodName = "/capsule.v1.GuestAgent/StartPayload"
	GuestAgent_Status_FullMethodName       = "/capsule.v1.GuestAgent/Status"
	GuestAgent_Logs_FullMethodName         = "/capsule.v1.GuestAgent/Logs"
	GuestAgent_Exec_FullMethodName         = "/capsule.v1.GuestAgent/Exec"
	GuestAgent_Stop_FullMethodName         = "/capsule.v1.GuestAgent/Stop"
)

// GuestAgentClient is the client API for GuestAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GuestAgent is the gRPC service exposed by capsule-guest inside every
// Capsule-managed microVM. capsuled on the host dials it over vsock to drive
// the VM's lifecycle: start the user payload, stream logs, exec one-off
// commands, stop it.
//
// The agent is PID 1 inside the VM. It owns /proc, /sys, /dev, and
// handles zombie reaping for the payload tree.
type GuestAgentClient interface {
	// Ping is a cheap liveness probe. Called by capsuled after VM boot to
	// detect when the agent is ready before issuing StartPayload.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// StartPayload mounts the attached payload block device at a known
	// path, sets env/cwd, and execs the entrypoint as a child process
	// (so the agent remains PID 1 and can observe it).
	StartPayload(ctx context.Context, in *StartPayloadRequest, opts ...grpc.CallOption) (*StartPayloadResponse, error)
	// Status returns the observed lifecycle of the currently-running
	// payload process. Returns UNSPECIFIED if nothing started yet.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Logs streams combined stdout+stderr of the payload process.
	// Supports follow and tail-lines semantics like WorkloadService.Logs.
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	// Exec runs a one-shot process in the payload's mount namespace.
	// Bidi-streaming, mirrors WorkloadService.Exec.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecClientMessage, ExecServerMessage], error)
	// Stop asks the payload to terminate. Sends SIGTERM, then SIGKILL
	// after grace_seconds.
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error)
}

type guestAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewGuestAgentClient(cc grpc.ClientConnInterface) GuestAgentClient {
	return &guestAgentClient{cc}
}

func (c *guestAgentClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) StartPayload(ctx context.Context, in *StartPayloadRequest, opts ...grpc.CallOption) (*StartPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartPayloadResponse)
	err := c.cc.Invoke(ctx, GuestAgent_StartPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *guestAgentClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[0], GuestAgent_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_LogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *guestAgentClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecClientMessage, ExecServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GuestAgent_ServiceDesc.Streams[1], GuestAgent_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecClientMessage, ExecServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_ExecClient = grpc.BidiStreamingClient[ExecClientMessage, ExecServerMessage]

func (c *guestAgentClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopResponse)
	err := c.cc.Invoke(ctx, GuestAgent_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GuestAgentServer is the server API for GuestAgent service.
// All implementations must embed UnimplementedGuestAgentServer
// for forward compatibility.
//
// GuestAgent is the gRPC service exposed by capsule-guest inside every
// Capsule-managed microVM. capsuled on the host dials it over vsock to drive
// the VM's lifecycle: start the user payload, stream logs, exec one-off
// commands, stop it.
//
// The agent is PID 1 inside the VM. It owns /proc, /sys, /dev, and
// handles zombie reaping for the payload tree.
type GuestAgentServer interface {
	// Ping is a cheap liveness probe. Called by capsuled after VM boot to
	// detect when the agent is ready before issuing StartPayload.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// StartPayload mounts the attached payload block device at a known
	// path, sets env/cwd, and execs the entrypoint as a child process
	// (so the agent remains PID 1 and can observe it).
	StartPayload(context.Context, *StartPayloadRequest) (*StartPayloadResponse, error)
	// Status returns the observed lifecycle of the currently-running
	// payload process. Returns UNSPECIFIED if nothing started yet.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Logs streams combined stdout+stderr of the payload process.
	// Supports follow and tail-lines semantics like WorkloadService.Logs.
	Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	// Exec runs a one-shot process in the payload's mount namespace.
	// Bidi-streaming, mirrors WorkloadService.Exec.
	Exec(grpc.BidiStreamingServer[ExecClientMessage, ExecServerMessage]) error
	// Stop asks the payload to terminate. Sends SIGTERM, then SIGKILL
	// after grace_seconds.
	Stop(context.Context, *StopRequest) (*StopResponse, error)
	mustEmbedUnimplementedGuestAgentServer()
}

// UnimplementedGuestAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGuestAgentServer struct{}

func (UnimplementedGuestAgentServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGuestAgentServer) StartPayload(context.Context, *StartPayloadRequest) (*StartPayloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartPayload not implemented")
}
func (UnimplementedGuestAgentServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedGuestAgentServer) Logs(*LogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedGuestAgentServer) Exec(grpc.BidiStreamingServer[ExecClientMessage, ExecServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedGuestAgentServer) Stop(context.Context, *StopRequest) (*StopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedGuestAgentServer) mustEmbedUnimplementedGuestAgentServer() {}
func (UnimplementedGuestAgentServer) testEmbeddedByValue()                    {}

// UnsafeGuestAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GuestAgentServer will
// result in compilation errors.
type UnsafeGuestAgentServer interface {
	mustEmbedUnimplementedGuestAgentServer()
}

func RegisterGuestAgentServer(s grpc.ServiceRegistrar, srv GuestAgentServer) {
	// If the following call panics, it indicates UnimplementedGuestAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GuestAgent_ServiceDesc, srv)
}

func _GuestAgent_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_StartPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).StartPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_StartPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).StartPayload(ctx, req.(*StartPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GuestAgent_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GuestAgentServer).Logs(m, &grpc.GenericServerStream[LogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_LogsServer = grpc.ServerStreamingServer[LogChunk]

func _GuestAgent_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GuestAgentServer).Exec(&grpc.GenericServerStream[ExecClientMessage, ExecServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GuestAgent_ExecServer = grpc.BidiStreamingServer[ExecClientMessage, ExecServerMessage]

func _GuestAgent_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GuestAgentServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GuestAgent_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GuestAgentServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GuestAgent_ServiceDesc is the grpc.ServiceDesc for GuestAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GuestAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capsule.v1.GuestAgent",
	HandlerType: (*GuestAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GuestAgent_Ping_Handler,
		},
		{
			MethodName: "StartPayload",
			Handler:    _GuestAgent_StartPayload_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _GuestAgent_Status_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _GuestAgent_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _GuestAgent_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _GuestAgent_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "capsule/v1/guest.proto",
}
