// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: capsule/v1/identity.proto

package capsulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_Adopt_FullMethodName     = "/capsule.v1.IdentityService/Adopt"
	IdentityService_WhoAmI_FullMethodName    = "/capsule.v1.IdentityService/WhoAmI"
	IdentityService_KeyAdd_FullMethodName    = "/capsule.v1.IdentityService/KeyAdd"
	IdentityService_KeyList_FullMethodName   = "/capsule.v1.IdentityService/KeyList"
	IdentityService_KeyRemove_FullMethodName = "/capsule.v1.IdentityService/KeyRemove"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService manages who is allowed to talk to this capsule. It is
// the only service whose Adopt RPC is callable without an authenticated
// JWT — and even Adopt is gated by a one-shot claim window that opens
// only when no operator keys are enrolled. After adoption, every RPC
// (here and on the other services) requires a bearer token signed by an
// enrolled key.
type IdentityServiceClient interface {
	// Adopt enrolls the caller's public key as the first authorized key on
	// a fresh capsule. Only callable while the claim window is open
	// (capsule has zero enrolled keys AND boot-time timer hasn't expired).
	// Closes the window on success. Returns the capsule's stable id and
	// the SHA-256 fingerprint of its TLS leaf cert so the client can pin
	// it for all subsequent dials.
	Adopt(ctx context.Context, in *AdoptRequest, opts ...grpc.CallOption) (*AdoptResponse, error)
	// WhoAmI returns the caller's enrolled identity (kid + name) along
	// with the capsule_id. Used by `capsulectl whoami` to confirm the
	// local context is wired correctly.
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
	// KeyAdd enrolls another operator's public key. Available to any
	// already-enrolled caller (flat trust model).
	KeyAdd(ctx context.Context, in *KeyAddRequest, opts ...grpc.CallOption) (*KeyAddResponse, error)
	// KeyList returns all enrolled keys (kid + metadata only — pubkey
	// bytes are not surfaced over the wire).
	KeyList(ctx context.Context, in *KeyListRequest, opts ...grpc.CallOption) (*KeyListResponse, error)
	// KeyRemove removes an enrolled key by kid. The server rejects the
	// call when only one key remains (would lock the capsule out forever
	// — operator must add a second key first or use the console RESET_AUTH
	// procedure).
	KeyRemove(ctx context.Context, in *KeyRemoveRequest, opts ...grpc.CallOption) (*KeyRemoveResponse, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) Adopt(ctx context.Context, in *AdoptRequest, opts ...grpc.CallOption) (*AdoptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdoptResponse)
	err := c.cc.Invoke(ctx, IdentityService_Adopt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, IdentityService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) KeyAdd(ctx context.Context, in *KeyAddRequest, opts ...grpc.CallOption) (*KeyAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyAddResponse)
	err := c.cc.Invoke(ctx, IdentityService_KeyAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) KeyList(ctx context.Context, in *KeyListRequest, opts ...grpc.CallOption) (*KeyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyListResponse)
	err := c.cc.Invoke(ctx, IdentityService_KeyList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) KeyRemove(ctx context.Context, in *KeyRemoveRequest, opts ...grpc.CallOption) (*KeyRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyRemoveResponse)
	err := c.cc.Invoke(ctx, IdentityService_KeyRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService manages who is allowed to talk to this capsule. It is
// the only service whose Adopt RPC is callable without an authenticated
// JWT — and even Adopt is gated by a one-shot claim window that opens
// only when no operator keys are enrolled. After adoption, every RPC
// (here and on the other services) requires a bearer token signed by an
// enrolled key.
type IdentityServiceServer interface {
	// Adopt enrolls the caller's public key as the first authorized key on
	// a fresh capsule. Only callable while the claim window is open
	// (capsule has zero enrolled keys AND boot-time timer hasn't expired).
	// Closes the window on success. Returns the capsule's stable id and
	// the SHA-256 fingerprint of its TLS leaf cert so the client can pin
	// it for all subsequent dials.
	Adopt(context.Context, *AdoptRequest) (*AdoptResponse, error)
	// WhoAmI returns the caller's enrolled identity (kid + name) along
	// with the capsule_id. Used by `capsulectl whoami` to confirm the
	// local context is wired correctly.
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
	// KeyAdd enrolls another operator's public key. Available to any
	// already-enrolled caller (flat trust model).
	KeyAdd(context.Context, *KeyAddRequest) (*KeyAddResponse, error)
	// KeyList returns all enrolled keys (kid + metadata only — pubkey
	// bytes are not surfaced over the wire).
	KeyList(context.Context, *KeyListRequest) (*KeyListResponse, error)
	// KeyRemove removes an enrolled key by kid. The server rejects the
	// call when only one key remains (would lock the capsule out forever
	// — operator must add a second key first or use the console RESET_AUTH
	// procedure).
	KeyRemove(context.Context, *KeyRemoveRequest) (*KeyRemoveResponse, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) Adopt(context.Context, *AdoptRequest) (*AdoptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Adopt not implemented")
}
func (UnimplementedIdentityServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedIdentityServiceServer) KeyAdd(context.Context, *KeyAddRequest) (*KeyAddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyAdd not implemented")
}
func (UnimplementedIdentityServiceServer) KeyList(context.Context, *KeyListRequest) (*KeyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyList not implemented")
}
func (UnimplementedIdentityServiceServer) KeyRemove(context.Context, *KeyRemoveRequest) (*KeyRemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KeyRemove not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_Adopt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdoptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).Adopt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_Adopt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).Adopt(ctx, req.(*AdoptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_KeyAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).KeyAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_KeyAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).KeyAdd(ctx, req.(*KeyAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_KeyList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).KeyList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_KeyList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).KeyList(ctx, req.(*KeyListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_KeyRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).KeyRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_KeyRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).KeyRemove(ctx, req.(*KeyRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capsule.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Adopt",
			Handler:    _IdentityService_Adopt_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _IdentityService_WhoAmI_Handler,
		},
		{
			MethodName: "KeyAdd",
			Handler:    _IdentityService_KeyAdd_Handler,
		},
		{
			MethodName: "KeyList",
			Handler:    _IdentityService_KeyList_Handler,
		},
		{
			MethodName: "KeyRemove",
			Handler:    _IdentityService_KeyRemove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capsule/v1/identity.proto",
}
