// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capsule/v1/identity.proto

package capsulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdoptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw 32-byte Ed25519 public key.
	Pubkey []byte `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	// Operator-friendly label ("laptop", "ci", etc).
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdoptRequest) Reset() {
	*x = AdoptRequest{}
	mi := &file_capsule_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptRequest) ProtoMessage() {}

func (x *AdoptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptRequest.ProtoReflect.Descriptor instead.
func (*AdoptRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *AdoptRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *AdoptRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AdoptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUIDv4 stable id of this capsule. Goes into JWT `aud`.
	CapsuleId string `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	// base64url(sha256(pubkey)), no padding — the kid the server assigned.
	Kid string `protobuf:"bytes,2,opt,name=kid,proto3" json:"kid,omitempty"`
	// SHA-256 of the server's TLS leaf cert DER, hex-encoded. The client
	// MUST cross-check this against the cert it saw on the wire to detect
	// a MITM that returns a forged response from behind its own cert.
	TlsFingerprintSha256 string `protobuf:"bytes,3,opt,name=tls_fingerprint_sha256,json=tlsFingerprintSha256,proto3" json:"tls_fingerprint_sha256,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AdoptResponse) Reset() {
	*x = AdoptResponse{}
	mi := &file_capsule_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdoptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdoptResponse) ProtoMessage() {}

func (x *AdoptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdoptResponse.ProtoReflect.Descriptor instead.
func (*AdoptResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *AdoptResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *AdoptResponse) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *AdoptResponse) GetTlsFingerprintSha256() string {
	if x != nil {
		return x.TlsFingerprintSha256
	}
	return ""
}

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_capsule_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{2}
}

type WhoAmIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CapsuleId     string                 `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	Kid           string                 `protobuf:"bytes,2,opt,name=kid,proto3" json:"kid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_capsule_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *WhoAmIResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *WhoAmIResponse) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *WhoAmIResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// AuthorizedKey is the wire-side view of an enrolled key. Pubkey bytes
// are intentionally absent — kid is the public identifier.
type AuthorizedKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kid           string                 `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AddedByKid    string                 `protobuf:"bytes,3,opt,name=added_by_kid,json=addedByKid,proto3" json:"added_by_kid,omitempty"`
	AddedAtUnix   int64                  `protobuf:"varint,4,opt,name=added_at_unix,json=addedAtUnix,proto3" json:"added_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizedKey) Reset() {
	*x = AuthorizedKey{}
	mi := &file_capsule_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizedKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizedKey) ProtoMessage() {}

func (x *AuthorizedKey) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizedKey.ProtoReflect.Descriptor instead.
func (*AuthorizedKey) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizedKey) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *AuthorizedKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorizedKey) GetAddedByKid() string {
	if x != nil {
		return x.AddedByKid
	}
	return ""
}

func (x *AuthorizedKey) GetAddedAtUnix() int64 {
	if x != nil {
		return x.AddedAtUnix
	}
	return 0
}

type KeyAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAddRequest) Reset() {
	*x = KeyAddRequest{}
	mi := &file_capsule_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAddRequest) ProtoMessage() {}

func (x *KeyAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAddRequest.ProtoReflect.Descriptor instead.
func (*KeyAddRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *KeyAddRequest) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *KeyAddRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type KeyAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *AuthorizedKey         `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAddResponse) Reset() {
	*x = KeyAddResponse{}
	mi := &file_capsule_v1_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAddResponse) ProtoMessage() {}

func (x *KeyAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAddResponse.ProtoReflect.Descriptor instead.
func (*KeyAddResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{6}
}

func (x *KeyAddResponse) GetKey() *AuthorizedKey {
	if x != nil {
		return x.Key
	}
	return nil
}

type KeyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyListRequest) Reset() {
	*x = KeyListRequest{}
	mi := &file_capsule_v1_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListRequest) ProtoMessage() {}

func (x *KeyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListRequest.ProtoReflect.Descriptor instead.
func (*KeyListRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{7}
}

type KeyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*AuthorizedKey       `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyListResponse) Reset() {
	*x = KeyListResponse{}
	mi := &file_capsule_v1_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyListResponse) ProtoMessage() {}

func (x *KeyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyListResponse.ProtoReflect.Descriptor instead.
func (*KeyListResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{8}
}

func (x *KeyListResponse) GetKeys() []*AuthorizedKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kid           string                 `protobuf:"bytes,1,opt,name=kid,proto3" json:"kid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRemoveRequest) Reset() {
	*x = KeyRemoveRequest{}
	mi := &file_capsule_v1_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRemoveRequest) ProtoMessage() {}

func (x *KeyRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRemoveRequest.ProtoReflect.Descriptor instead.
func (*KeyRemoveRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{9}
}

func (x *KeyRemoveRequest) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

type KeyRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRemoveResponse) Reset() {
	*x = KeyRemoveResponse{}
	mi := &file_capsule_v1_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRemoveResponse) ProtoMessage() {}

func (x *KeyRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRemoveResponse.ProtoReflect.Descriptor instead.
func (*KeyRemoveResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_identity_proto_rawDescGZIP(), []int{10}
}

var File_capsule_v1_identity_proto protoreflect.FileDescriptor

const file_capsule_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\x19capsule/v1/identity.proto\x12\n" +
	"capsule.v1\":\n" +
	"\fAdoptRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"v\n" +
	"\rAdoptResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x10\n" +
	"\x03kid\x18\x02 \x01(\tR\x03kid\x124\n" +
	"\x16tls_fingerprint_sha256\x18\x03 \x01(\tR\x14tlsFingerprintSha256\"\x0f\n" +
	"\rWhoAmIRequest\"U\n" +
	"\x0eWhoAmIResponse\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x12\x10\n" +
	"\x03kid\x18\x02 \x01(\tR\x03kid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"{\n" +
	"\rAuthorizedKey\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\fadded_by_kid\x18\x03 \x01(\tR\n" +
	"addedByKid\x12\"\n" +
	"\radded_at_unix\x18\x04 \x01(\x03R\vaddedAtUnix\";\n" +
	"\rKeyAddRequest\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"=\n" +
	"\x0eKeyAddResponse\x12+\n" +
	"\x03key\x18\x01 \x01(\v2\x19.capsule.v1.AuthorizedKeyR\x03key\"\x10\n" +
	"\x0eKeyListRequest\"@\n" +
	"\x0fKeyListResponse\x12-\n" +
	"\x04keys\x18\x01 \x03(\v2\x19.capsule.v1.AuthorizedKeyR\x04keys\"$\n" +
	"\x10KeyRemoveRequest\x12\x10\n" +
	"\x03kid\x18\x01 \x01(\tR\x03kid\"\x13\n" +
	"\x11KeyRemoveResponse2\xdf\x02\n" +
	"\x0fIdentityService\x12<\n" +
	"\x05Adopt\x12\x18.capsule.v1.AdoptRequest\x1a\x19.capsule.v1.AdoptResponse\x12?\n" +
	"\x06WhoAmI\x12\x19.capsule.v1.WhoAmIRequest\x1a\x1a.capsule.v1.WhoAmIResponse\x12?\n" +
	"\x06KeyAdd\x12\x19.capsule.v1.KeyAddRequest\x1a\x1a.capsule.v1.KeyAddResponse\x12B\n" +
	"\aKeyList\x12\x1a.capsule.v1.KeyListRequest\x1a\x1b.capsule.v1.KeyListResponse\x12H\n" +
	"\tKeyRemove\x12\x1c.capsule.v1.KeyRemoveRequest\x1a\x1d.capsule.v1.KeyRemoveResponseB\xa6\x01\n" +
	"\x0ecom.capsule.v1B\rIdentityProtoP\x01Z<github.com/geekgonecrazy/capsule/models/capsule/v1;capsulev1\xa2\x02\x03CXX\xaa\x02\n" +
	"Capsule.V1\xca\x02\n" +
	"Capsule\\V1\xe2\x02\x16Capsule\\V1\\GPBMetadata\xea\x02\vCapsule::V1b\x06proto3"

var (
	file_capsule_v1_identity_proto_rawDescOnce sync.Once
	file_capsule_v1_identity_proto_rawDescData []byte
)

func file_capsule_v1_identity_proto_rawDescGZIP() []byte {
	file_capsule_v1_identity_proto_rawDescOnce.Do(func() {
		file_capsule_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capsule_v1_identity_proto_rawDesc), len(file_capsule_v1_identity_proto_rawDesc)))
	})
	return file_capsule_v1_identity_proto_rawDescData
}

var file_capsule_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_capsule_v1_identity_proto_goTypes = []any{
	(*AdoptRequest)(nil),      // 0: capsule.v1.AdoptRequest
	(*AdoptResponse)(nil),     // 1: capsule.v1.AdoptResponse
	(*WhoAmIRequest)(nil),     // 2: capsule.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),    // 3: capsule.v1.WhoAmIResponse
	(*AuthorizedKey)(nil),     // 4: capsule.v1.AuthorizedKey
	(*KeyAddRequest)(nil),     // 5: capsule.v1.KeyAddRequest
	(*KeyAddResponse)(nil),    // 6: capsule.v1.KeyAddResponse
	(*KeyListRequest)(nil),    // 7: capsule.v1.KeyListRequest
	(*KeyListResponse)(nil),   // 8: capsule.v1.KeyListResponse
	(*KeyRemoveRequest)(nil),  // 9: capsule.v1.KeyRemoveRequest
	(*KeyRemoveResponse)(nil), // 10: capsule.v1.KeyRemoveResponse
}
var file_capsule_v1_identity_proto_depIdxs = []int32{
	4,  // 0: capsule.v1.KeyAddResponse.key:type_name -> capsule.v1.AuthorizedKey
	4,  // 1: capsule.v1.KeyListResponse.keys:type_name -> capsule.v1.AuthorizedKey
	0,  // 2: capsule.v1.IdentityService.Adopt:input_type -> capsule.v1.AdoptRequest
	2,  // 3: capsule.v1.IdentityService.WhoAmI:input_type -> capsule.v1.WhoAmIRequest
	5,  // 4: capsule.v1.IdentityService.KeyAdd:input_type -> capsule.v1.KeyAddRequest
	7,  // 5: capsule.v1.IdentityService.KeyList:input_type -> capsule.v1.KeyListRequest
	9,  // 6: capsule.v1.IdentityService.KeyRemove:input_type -> capsule.v1.KeyRemoveRequest
	1,  // 7: capsule.v1.IdentityService.Adopt:output_type -> capsule.v1.AdoptResponse
	3,  // 8: capsule.v1.IdentityService.WhoAmI:output_type -> capsule.v1.WhoAmIResponse
	6,  // 9: capsule.v1.IdentityService.KeyAdd:output_type -> capsule.v1.KeyAddResponse
	8,  // 10: capsule.v1.IdentityService.KeyList:output_type -> capsule.v1.KeyListResponse
	10, // 11: capsule.v1.IdentityService.KeyRemove:output_type -> capsule.v1.KeyRemoveResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_capsule_v1_identity_proto_init() }
func file_capsule_v1_identity_proto_init() {
	if File_capsule_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capsule_v1_identity_proto_rawDesc), len(file_capsule_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capsule_v1_identity_proto_goTypes,
		DependencyIndexes: file_capsule_v1_identity_proto_depIdxs,
		MessageInfos:      file_capsule_v1_identity_proto_msgTypes,
	}.Build()
	File_capsule_v1_identity_proto = out.File
	file_capsule_v1_identity_proto_goTypes = nil
	file_capsule_v1_identity_proto_depIdxs = nil
}
