// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: capsule/v1/image.proto

package capsulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ImageService_List_FullMethodName = "/capsule.v1.ImageService/List"
	ImageService_Push_FullMethodName = "/capsule.v1.ImageService/Push"
)

// ImageServiceClient is the client API for ImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ImageService manages OCI images in the capsule's containerd image
// store. Use it to push images that aren't available in any registry the
// capsule can reach (private images, air-gapped builds, work-in-progress
// images you haven't pushed anywhere yet) and to inspect what's already
// cached on the capsule.
type ImageServiceClient interface {
	// List returns every image known to containerd in the `capsule`
	// namespace — both registry-pulled and operator-pushed.
	List(ctx context.Context, in *ImageListRequest, opts ...grpc.CallOption) (*ImageListResponse, error)
	// Push streams an OCI/docker-save tar archive from the operator into
	// containerd's image store. The first client message MUST be
	// ImagePushRequest.metadata; subsequent messages carry tar bytes.
	// Equivalent to `docker load` / `ctr image import`. After import the
	// server unpacks each ref into the snapshotter so it's ready to back
	// a container without a separate pull.
	Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImagePushRequest, ImagePushResponse], error)
}

type imageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewImageServiceClient(cc grpc.ClientConnInterface) ImageServiceClient {
	return &imageServiceClient{cc}
}

func (c *imageServiceClient) List(ctx context.Context, in *ImageListRequest, opts ...grpc.CallOption) (*ImageListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImageListResponse)
	err := c.cc.Invoke(ctx, ImageService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imageServiceClient) Push(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImagePushRequest, ImagePushResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ImageService_ServiceDesc.Streams[0], ImageService_Push_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImagePushRequest, ImagePushResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageService_PushClient = grpc.ClientStreamingClient[ImagePushRequest, ImagePushResponse]

// ImageServiceServer is the server API for ImageService service.
// All implementations must embed UnimplementedImageServiceServer
// for forward compatibility.
//
// ImageService manages OCI images in the capsule's containerd image
// store. Use it to push images that aren't available in any registry the
// capsule can reach (private images, air-gapped builds, work-in-progress
// images you haven't pushed anywhere yet) and to inspect what's already
// cached on the capsule.
type ImageServiceServer interface {
	// List returns every image known to containerd in the `capsule`
	// namespace — both registry-pulled and operator-pushed.
	List(context.Context, *ImageListRequest) (*ImageListResponse, error)
	// Push streams an OCI/docker-save tar archive from the operator into
	// containerd's image store. The first client message MUST be
	// ImagePushRequest.metadata; subsequent messages carry tar bytes.
	// Equivalent to `docker load` / `ctr image import`. After import the
	// server unpacks each ref into the snapshotter so it's ready to back
	// a container without a separate pull.
	Push(grpc.ClientStreamingServer[ImagePushRequest, ImagePushResponse]) error
	mustEmbedUnimplementedImageServiceServer()
}

// UnimplementedImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedImageServiceServer struct{}

func (UnimplementedImageServiceServer) List(context.Context, *ImageListRequest) (*ImageListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedImageServiceServer) Push(grpc.ClientStreamingServer[ImagePushRequest, ImagePushResponse]) error {
	return status.Error(codes.Unimplemented, "method Push not implemented")
}
func (UnimplementedImageServiceServer) mustEmbedUnimplementedImageServiceServer() {}
func (UnimplementedImageServiceServer) testEmbeddedByValue()                      {}

// UnsafeImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServiceServer will
// result in compilation errors.
type UnsafeImageServiceServer interface {
	mustEmbedUnimplementedImageServiceServer()
}

func RegisterImageServiceServer(s grpc.ServiceRegistrar, srv ImageServiceServer) {
	// If the following call panics, it indicates UnimplementedImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ImageService_ServiceDesc, srv)
}

func _ImageService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ImageService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageServiceServer).List(ctx, req.(*ImageListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ImageService_Push_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServiceServer).Push(&grpc.GenericServerStream[ImagePushRequest, ImagePushResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ImageService_PushServer = grpc.ClientStreamingServer[ImagePushRequest, ImagePushResponse]

// ImageService_ServiceDesc is the grpc.ServiceDesc for ImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capsule.v1.ImageService",
	HandlerType: (*ImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _ImageService_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Push",
			Handler:       _ImageService_Push_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "capsule/v1/image.proto",
}
