// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capsule/v1/image.proto

package capsulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageListRequest) Reset() {
	*x = ImageListRequest{}
	mi := &file_capsule_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListRequest) ProtoMessage() {}

func (x *ImageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListRequest.ProtoReflect.Descriptor instead.
func (*ImageListRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_image_proto_rawDescGZIP(), []int{0}
}

type ImageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Images        []*Image               `protobuf:"bytes,1,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageListResponse) Reset() {
	*x = ImageListResponse{}
	mi := &file_capsule_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageListResponse) ProtoMessage() {}

func (x *ImageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageListResponse.ProtoReflect.Descriptor instead.
func (*ImageListResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageListResponse) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Image struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully-qualified ref, e.g. "docker.io/library/alpine:3.20" or
	// "myhost/myapp:dev".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Manifest digest, e.g. "sha256:abc123…".
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	// Total size of the image's content (manifest + config + layers) in
	// bytes, as reported by containerd's content store.
	SizeBytes int64 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	// Image creation time in Unix seconds (containerd's UpdatedAt — rises
	// when an image is re-pushed).
	CreatedUnix   int64 `protobuf:"varint,4,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_capsule_v1_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_capsule_v1_image_proto_rawDescGZIP(), []int{2}
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Image) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *Image) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

type ImagePushRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ImagePushRequest_Metadata
	//	*ImagePushRequest_Chunk
	Msg           isImagePushRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePushRequest) Reset() {
	*x = ImagePushRequest{}
	mi := &file_capsule_v1_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePushRequest) ProtoMessage() {}

func (x *ImagePushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePushRequest.ProtoReflect.Descriptor instead.
func (*ImagePushRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_image_proto_rawDescGZIP(), []int{3}
}

func (x *ImagePushRequest) GetMsg() isImagePushRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ImagePushRequest) GetMetadata() *ImagePushMetadata {
	if x != nil {
		if x, ok := x.Msg.(*ImagePushRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *ImagePushRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Msg.(*ImagePushRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isImagePushRequest_Msg interface {
	isImagePushRequest_Msg()
}

type ImagePushRequest_Metadata struct {
	Metadata *ImagePushMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // first message only
}

type ImagePushRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // streaming tar bytes
}

func (*ImagePushRequest_Metadata) isImagePushRequest_Msg() {}

func (*ImagePushRequest_Chunk) isImagePushRequest_Msg() {}

type ImagePushMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total archive size in bytes. Optional but lets the server pre-size
	// any internal buffers and surface progress.
	TotalBytes    uint64 `protobuf:"varint,1,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePushMetadata) Reset() {
	*x = ImagePushMetadata{}
	mi := &file_capsule_v1_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePushMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePushMetadata) ProtoMessage() {}

func (x *ImagePushMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePushMetadata.ProtoReflect.Descriptor instead.
func (*ImagePushMetadata) Descriptor() ([]byte, []int) {
	return file_capsule_v1_image_proto_rawDescGZIP(), []int{4}
}

func (x *ImagePushMetadata) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type ImagePushResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Refs the server discovered in the archive and registered into the
	// image store. Empty if the archive contained no image manifests.
	ImageRefs []string `protobuf:"bytes,1,rep,name=image_refs,json=imageRefs,proto3" json:"image_refs,omitempty"`
	// Total tar bytes received from the client.
	BytesReceived uint64 `protobuf:"varint,2,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePushResponse) Reset() {
	*x = ImagePushResponse{}
	mi := &file_capsule_v1_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePushResponse) ProtoMessage() {}

func (x *ImagePushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePushResponse.ProtoReflect.Descriptor instead.
func (*ImagePushResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_image_proto_rawDescGZIP(), []int{5}
}

func (x *ImagePushResponse) GetImageRefs() []string {
	if x != nil {
		return x.ImageRefs
	}
	return nil
}

func (x *ImagePushResponse) GetBytesReceived() uint64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

var File_capsule_v1_image_proto protoreflect.FileDescriptor

const file_capsule_v1_image_proto_rawDesc = "" +
	"\n" +
	"\x16capsule/v1/image.proto\x12\n" +
	"capsule.v1\"\x12\n" +
	"\x10ImageListRequest\">\n" +
	"\x11ImageListResponse\x12)\n" +
	"\x06images\x18\x01 \x03(\v2\x11.capsule.v1.ImageR\x06images\"u\n" +
	"\x05Image\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcreated_unix\x18\x04 \x01(\x03R\vcreatedUnix\"n\n" +
	"\x10ImagePushRequest\x12;\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1d.capsule.v1.ImagePushMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x05\n" +
	"\x03msg\"4\n" +
	"\x11ImagePushMetadata\x12\x1f\n" +
	"\vtotal_bytes\x18\x01 \x01(\x04R\n" +
	"totalBytes\"Y\n" +
	"\x11ImagePushResponse\x12\x1d\n" +
	"\n" +
	"image_refs\x18\x01 \x03(\tR\timageRefs\x12%\n" +
	"\x0ebytes_received\x18\x02 \x01(\x04R\rbytesReceived2\x9a\x01\n" +
	"\fImageService\x12C\n" +
	"\x04List\x12\x1c.capsule.v1.ImageListRequest\x1a\x1d.capsule.v1.ImageListResponse\x12E\n" +
	"\x04Push\x12\x1c.capsule.v1.ImagePushRequest\x1a\x1d.capsule.v1.ImagePushResponse(\x01B\xa3\x01\n" +
	"\x0ecom.capsule.v1B\n" +
	"ImageProtoP\x01Z<github.com/geekgonecrazy/capsule/models/capsule/v1;capsulev1\xa2\x02\x03CXX\xaa\x02\n" +
	"Capsule.V1\xca\x02\n" +
	"Capsule\\V1\xe2\x02\x16Capsule\\V1\\GPBMetadata\xea\x02\vCapsule::V1b\x06proto3"

var (
	file_capsule_v1_image_proto_rawDescOnce sync.Once
	file_capsule_v1_image_proto_rawDescData []byte
)

func file_capsule_v1_image_proto_rawDescGZIP() []byte {
	file_capsule_v1_image_proto_rawDescOnce.Do(func() {
		file_capsule_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capsule_v1_image_proto_rawDesc), len(file_capsule_v1_image_proto_rawDesc)))
	})
	return file_capsule_v1_image_proto_rawDescData
}

var file_capsule_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_capsule_v1_image_proto_goTypes = []any{
	(*ImageListRequest)(nil),  // 0: capsule.v1.ImageListRequest
	(*ImageListResponse)(nil), // 1: capsule.v1.ImageListResponse
	(*Image)(nil),             // 2: capsule.v1.Image
	(*ImagePushRequest)(nil),  // 3: capsule.v1.ImagePushRequest
	(*ImagePushMetadata)(nil), // 4: capsule.v1.ImagePushMetadata
	(*ImagePushResponse)(nil), // 5: capsule.v1.ImagePushResponse
}
var file_capsule_v1_image_proto_depIdxs = []int32{
	2, // 0: capsule.v1.ImageListResponse.images:type_name -> capsule.v1.Image
	4, // 1: capsule.v1.ImagePushRequest.metadata:type_name -> capsule.v1.ImagePushMetadata
	0, // 2: capsule.v1.ImageService.List:input_type -> capsule.v1.ImageListRequest
	3, // 3: capsule.v1.ImageService.Push:input_type -> capsule.v1.ImagePushRequest
	1, // 4: capsule.v1.ImageService.List:output_type -> capsule.v1.ImageListResponse
	5, // 5: capsule.v1.ImageService.Push:output_type -> capsule.v1.ImagePushResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_capsule_v1_image_proto_init() }
func file_capsule_v1_image_proto_init() {
	if File_capsule_v1_image_proto != nil {
		return
	}
	file_capsule_v1_image_proto_msgTypes[3].OneofWrappers = []any{
		(*ImagePushRequest_Metadata)(nil),
		(*ImagePushRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capsule_v1_image_proto_rawDesc), len(file_capsule_v1_image_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capsule_v1_image_proto_goTypes,
		DependencyIndexes: file_capsule_v1_image_proto_depIdxs,
		MessageInfos:      file_capsule_v1_image_proto_msgTypes,
	}.Build()
	File_capsule_v1_image_proto = out.File
	file_capsule_v1_image_proto_goTypes = nil
	file_capsule_v1_image_proto_depIdxs = nil
}
