// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capsule/v1/install.proto

package capsulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallStatusRequest) Reset() {
	*x = InstallStatusRequest{}
	mi := &file_capsule_v1_install_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallStatusRequest) ProtoMessage() {}

func (x *InstallStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_install_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallStatusRequest.ProtoReflect.Descriptor instead.
func (*InstallStatusRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_install_proto_rawDescGZIP(), []int{0}
}

type InstallStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable short handle for the installer ("capsule-a3f2"). Different
	// from the eventual disk-booted capsule's short_id, which is
	// generated by Install.
	ShortId string `protobuf:"bytes,1,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	// Capsule ID of the installer itself. Distinct from the future disk
	// identity; only meaningful while the USB is booted.
	CapsuleId string `protobuf:"bytes,2,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	// Auto-selected candidate target. Always set when there's at least
	// one viable target.
	TargetDisk string `protobuf:"bytes,3,opt,name=target_disk,json=targetDisk,proto3" json:"target_disk,omitempty"`
	// Byte size of the auto-selected target.
	TargetSizeBytes uint64 `protobuf:"varint,4,opt,name=target_size_bytes,json=targetSizeBytes,proto3" json:"target_size_bytes,omitempty"`
	// Full candidate list, including the auto-selected one. Operators
	// pass --target to pick a non-default disk; the CLI cross-checks
	// their choice against this list.
	Targets []string `protobuf:"bytes,5,rep,name=targets,proto3" json:"targets,omitempty"`
	// Build identifier of the running capsuled binary. The disk-booted
	// capsule will report the same version (it's the same squashfs).
	Version       string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallStatusResponse) Reset() {
	*x = InstallStatusResponse{}
	mi := &file_capsule_v1_install_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallStatusResponse) ProtoMessage() {}

func (x *InstallStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_install_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallStatusResponse.ProtoReflect.Descriptor instead.
func (*InstallStatusResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_install_proto_rawDescGZIP(), []int{1}
}

func (x *InstallStatusResponse) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

func (x *InstallStatusResponse) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *InstallStatusResponse) GetTargetDisk() string {
	if x != nil {
		return x.TargetDisk
	}
	return ""
}

func (x *InstallStatusResponse) GetTargetSizeBytes() uint64 {
	if x != nil {
		return x.TargetSizeBytes
	}
	return 0
}

func (x *InstallStatusResponse) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *InstallStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type InstallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Target /dev path. Must be in InstallStatusResponse.targets. If
	// empty, the installer auto-picks targets[0] (the default that
	// appears in `discover` and on the HDMI banner).
	TargetDisk string `protobuf:"bytes,1,opt,name=target_disk,json=targetDisk,proto3" json:"target_disk,omitempty"`
	// Operator's raw 32-byte Ed25519 public key. Sealed into the new
	// disk's PERM partition so the disk-booted capsule comes up with
	// this key already enrolled. Ignored when seal=false.
	OperatorPubkey []byte `protobuf:"bytes,2,opt,name=operator_pubkey,json=operatorPubkey,proto3" json:"operator_pubkey,omitempty"`
	// Operator-friendly label for the sealed key ("nuc-1"). Stored in
	// authorized_keys.name on the disk-booted capsule.
	OperatorName string `protobuf:"bytes,3,opt,name=operator_name,json=operatorName,proto3" json:"operator_name,omitempty"`
	// When true (the default), seed /perm/firstboot.json on the target
	// disk with the operator pubkey, a freshly-generated capsule_id, and
	// a freshly-generated TLS keypair so the disk boots already adopted.
	// When false, the installer writes a fresh image with no pre-seed —
	// the disk will open its own claim window on first boot.
	Seal bool `protobuf:"varint,4,opt,name=seal,proto3" json:"seal,omitempty"`
	// Force re-install on a target that already has a Capsule MBR. v1
	// default behavior refuses without this flag (avoid blowing away
	// someone's data by accident). Reserved; not currently enforced.
	Reinstall     bool `protobuf:"varint,5,opt,name=reinstall,proto3" json:"reinstall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallRequest) Reset() {
	*x = InstallRequest{}
	mi := &file_capsule_v1_install_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallRequest) ProtoMessage() {}

func (x *InstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_install_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallRequest.ProtoReflect.Descriptor instead.
func (*InstallRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_install_proto_rawDescGZIP(), []int{2}
}

func (x *InstallRequest) GetTargetDisk() string {
	if x != nil {
		return x.TargetDisk
	}
	return ""
}

func (x *InstallRequest) GetOperatorPubkey() []byte {
	if x != nil {
		return x.OperatorPubkey
	}
	return nil
}

func (x *InstallRequest) GetOperatorName() string {
	if x != nil {
		return x.OperatorName
	}
	return ""
}

func (x *InstallRequest) GetSeal() bool {
	if x != nil {
		return x.Seal
	}
	return false
}

func (x *InstallRequest) GetReinstall() bool {
	if x != nil {
		return x.Reinstall
	}
	return false
}

type InstallProgress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Phase identifier — one of: "verify", "partition", "format_boot",
	// "write_slot_a", "write_slot_b", "install_grub", "seal_firstboot",
	// "sync", "done". Phases run in this order; "done" is always the
	// final message, sent regardless of how the operator's CLI renders
	// progress.
	Phase string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// 0..100, monotonically increasing within a phase. The CLI renders
	// this as a progress bar; the percent resets to 0 when the phase
	// changes.
	Percent uint32 `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`
	// Human-readable message ("writing 64 MiB of 2048 MiB to slot_a").
	// Allowed to be empty between progress ticks within a phase.
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// Populated only on the terminal "done" event. Identifies the
	// capsule that will come up when the operator power-cycles into the
	// freshly-flashed disk.
	Result        *InstallResult `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallProgress) Reset() {
	*x = InstallProgress{}
	mi := &file_capsule_v1_install_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallProgress) ProtoMessage() {}

func (x *InstallProgress) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_install_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallProgress.ProtoReflect.Descriptor instead.
func (*InstallProgress) Descriptor() ([]byte, []int) {
	return file_capsule_v1_install_proto_rawDescGZIP(), []int{3}
}

func (x *InstallProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *InstallProgress) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *InstallProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InstallProgress) GetResult() *InstallResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type InstallResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable UUID generated by the installer for the disk-booted
	// capsule. Operator's context entry pins this so a successful
	// adopt-after-install always matches.
	CapsuleId string `protobuf:"bytes,1,opt,name=capsule_id,json=capsuleId,proto3" json:"capsule_id,omitempty"`
	// SHA-256 of the TLS leaf certificate the disk-booted capsule will
	// present. Pre-generated by the installer and seeded onto /perm so
	// the operator's context entry pins it correctly without needing a
	// second TOFU prompt after reboot.
	TlsFingerprintSha256 string `protobuf:"bytes,2,opt,name=tls_fingerprint_sha256,json=tlsFingerprintSha256,proto3" json:"tls_fingerprint_sha256,omitempty"`
	// base64url(sha256(operator_pubkey)) — the kid under which the
	// operator's key was sealed. Echoed so the CLI can confirm the key
	// shipped to the disk matches the one it generated locally.
	Kid string `protobuf:"bytes,3,opt,name=kid,proto3" json:"kid,omitempty"`
	// Stable handle for the disk-booted capsule ("capsule-a3f2"). Shown
	// in next-steps messaging so the operator knows what to look for in
	// `discover` output after pulling the USB.
	ShortId       string `protobuf:"bytes,4,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallResult) Reset() {
	*x = InstallResult{}
	mi := &file_capsule_v1_install_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallResult) ProtoMessage() {}

func (x *InstallResult) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_install_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallResult.ProtoReflect.Descriptor instead.
func (*InstallResult) Descriptor() ([]byte, []int) {
	return file_capsule_v1_install_proto_rawDescGZIP(), []int{4}
}

func (x *InstallResult) GetCapsuleId() string {
	if x != nil {
		return x.CapsuleId
	}
	return ""
}

func (x *InstallResult) GetTlsFingerprintSha256() string {
	if x != nil {
		return x.TlsFingerprintSha256
	}
	return ""
}

func (x *InstallResult) GetKid() string {
	if x != nil {
		return x.Kid
	}
	return ""
}

func (x *InstallResult) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

var File_capsule_v1_install_proto protoreflect.FileDescriptor

const file_capsule_v1_install_proto_rawDesc = "" +
	"\n" +
	"\x18capsule/v1/install.proto\x12\n" +
	"capsule.v1\"\x16\n" +
	"\x14InstallStatusRequest\"\xd2\x01\n" +
	"\x15InstallStatusResponse\x12\x19\n" +
	"\bshort_id\x18\x01 \x01(\tR\ashortId\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x02 \x01(\tR\tcapsuleId\x12\x1f\n" +
	"\vtarget_disk\x18\x03 \x01(\tR\n" +
	"targetDisk\x12*\n" +
	"\x11target_size_bytes\x18\x04 \x01(\x04R\x0ftargetSizeBytes\x12\x18\n" +
	"\atargets\x18\x05 \x03(\tR\atargets\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\"\xb1\x01\n" +
	"\x0eInstallRequest\x12\x1f\n" +
	"\vtarget_disk\x18\x01 \x01(\tR\n" +
	"targetDisk\x12'\n" +
	"\x0foperator_pubkey\x18\x02 \x01(\fR\x0eoperatorPubkey\x12#\n" +
	"\roperator_name\x18\x03 \x01(\tR\foperatorName\x12\x12\n" +
	"\x04seal\x18\x04 \x01(\bR\x04seal\x12\x1c\n" +
	"\treinstall\x18\x05 \x01(\bR\treinstall\"\x8e\x01\n" +
	"\x0fInstallProgress\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12\x18\n" +
	"\apercent\x18\x02 \x01(\rR\apercent\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x121\n" +
	"\x06result\x18\x04 \x01(\v2\x19.capsule.v1.InstallResultR\x06result\"\x91\x01\n" +
	"\rInstallResult\x12\x1d\n" +
	"\n" +
	"capsule_id\x18\x01 \x01(\tR\tcapsuleId\x124\n" +
	"\x16tls_fingerprint_sha256\x18\x02 \x01(\tR\x14tlsFingerprintSha256\x12\x10\n" +
	"\x03kid\x18\x03 \x01(\tR\x03kid\x12\x19\n" +
	"\bshort_id\x18\x04 \x01(\tR\ashortId2\xa5\x01\n" +
	"\x0eInstallService\x12M\n" +
	"\x06Status\x12 .capsule.v1.InstallStatusRequest\x1a!.capsule.v1.InstallStatusResponse\x12D\n" +
	"\aInstall\x12\x1a.capsule.v1.InstallRequest\x1a\x1b.capsule.v1.InstallProgress0\x01B\xa5\x01\n" +
	"\x0ecom.capsule.v1B\fInstallProtoP\x01Z<github.com/geekgonecrazy/capsule/models/capsule/v1;capsulev1\xa2\x02\x03CXX\xaa\x02\n" +
	"Capsule.V1\xca\x02\n" +
	"Capsule\\V1\xe2\x02\x16Capsule\\V1\\GPBMetadata\xea\x02\vCapsule::V1b\x06proto3"

var (
	file_capsule_v1_install_proto_rawDescOnce sync.Once
	file_capsule_v1_install_proto_rawDescData []byte
)

func file_capsule_v1_install_proto_rawDescGZIP() []byte {
	file_capsule_v1_install_proto_rawDescOnce.Do(func() {
		file_capsule_v1_install_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capsule_v1_install_proto_rawDesc), len(file_capsule_v1_install_proto_rawDesc)))
	})
	return file_capsule_v1_install_proto_rawDescData
}

var file_capsule_v1_install_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_capsule_v1_install_proto_goTypes = []any{
	(*InstallStatusRequest)(nil),  // 0: capsule.v1.InstallStatusRequest
	(*InstallStatusResponse)(nil), // 1: capsule.v1.InstallStatusResponse
	(*InstallRequest)(nil),        // 2: capsule.v1.InstallRequest
	(*InstallProgress)(nil),       // 3: capsule.v1.InstallProgress
	(*InstallResult)(nil),         // 4: capsule.v1.InstallResult
}
var file_capsule_v1_install_proto_depIdxs = []int32{
	4, // 0: capsule.v1.InstallProgress.result:type_name -> capsule.v1.InstallResult
	0, // 1: capsule.v1.InstallService.Status:input_type -> capsule.v1.InstallStatusRequest
	2, // 2: capsule.v1.InstallService.Install:input_type -> capsule.v1.InstallRequest
	1, // 3: capsule.v1.InstallService.Status:output_type -> capsule.v1.InstallStatusResponse
	3, // 4: capsule.v1.InstallService.Install:output_type -> capsule.v1.InstallProgress
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_capsule_v1_install_proto_init() }
func file_capsule_v1_install_proto_init() {
	if File_capsule_v1_install_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capsule_v1_install_proto_rawDesc), len(file_capsule_v1_install_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capsule_v1_install_proto_goTypes,
		DependencyIndexes: file_capsule_v1_install_proto_depIdxs,
		MessageInfos:      file_capsule_v1_install_proto_msgTypes,
	}.Build()
	File_capsule_v1_install_proto = out.File
	file_capsule_v1_install_proto_goTypes = nil
	file_capsule_v1_install_proto_depIdxs = nil
}
