// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: capsule/v1/install.proto

package capsulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstallService_Status_FullMethodName  = "/capsule.v1.InstallService/Status"
	InstallService_Install_FullMethodName = "/capsule.v1.InstallService/Install"
)

// InstallServiceClient is the client API for InstallService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InstallService is exposed *only* when capsuled is running in installer
// mode (USB-booted on a machine with a viable internal install target).
// On a runtime capsule the service is not registered; clients calling
// it receive Unimplemented.
//
// The service is unauthenticated. Pre-adoption, there is no operator
// key on the capsule to verify against — physical access to the USB +
// presence on the LAN is the trust boundary, the same posture as the
// claim window today. The operator validates the installer's TLS
// fingerprint against the HDMI banner before triggering a flash.
type InstallServiceClient interface {
	// Status returns installer-mode metadata for a capsule. Used by
	// `capsulectl install --addr` when mDNS isn't available — the CLI
	// confirms the target is actually an installer before sealing a
	// key. Runtime capsules don't register InstallService at all, so
	// calling Status against one fails with Unimplemented.
	Status(ctx context.Context, in *InstallStatusRequest, opts ...grpc.CallOption) (*InstallStatusResponse, error)
	// Install flashes a target disk with a fresh Capsule image and
	// optionally seeds it with the operator's pubkey so the disk-booted
	// capsule comes up already adopted. Server-streams progress events;
	// the final event carries the disk-booted capsule's future identity
	// so the CLI can write a context entry that will resolve once the
	// operator removes the USB and reboots.
	Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstallProgress], error)
}

type installServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInstallServiceClient(cc grpc.ClientConnInterface) InstallServiceClient {
	return &installServiceClient{cc}
}

func (c *installServiceClient) Status(ctx context.Context, in *InstallStatusRequest, opts ...grpc.CallOption) (*InstallStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallStatusResponse)
	err := c.cc.Invoke(ctx, InstallService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *installServiceClient) Install(ctx context.Context, in *InstallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstallProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InstallService_ServiceDesc.Streams[0], InstallService_Install_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InstallRequest, InstallProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstallService_InstallClient = grpc.ServerStreamingClient[InstallProgress]

// InstallServiceServer is the server API for InstallService service.
// All implementations must embed UnimplementedInstallServiceServer
// for forward compatibility.
//
// InstallService is exposed *only* when capsuled is running in installer
// mode (USB-booted on a machine with a viable internal install target).
// On a runtime capsule the service is not registered; clients calling
// it receive Unimplemented.
//
// The service is unauthenticated. Pre-adoption, there is no operator
// key on the capsule to verify against — physical access to the USB +
// presence on the LAN is the trust boundary, the same posture as the
// claim window today. The operator validates the installer's TLS
// fingerprint against the HDMI banner before triggering a flash.
type InstallServiceServer interface {
	// Status returns installer-mode metadata for a capsule. Used by
	// `capsulectl install --addr` when mDNS isn't available — the CLI
	// confirms the target is actually an installer before sealing a
	// key. Runtime capsules don't register InstallService at all, so
	// calling Status against one fails with Unimplemented.
	Status(context.Context, *InstallStatusRequest) (*InstallStatusResponse, error)
	// Install flashes a target disk with a fresh Capsule image and
	// optionally seeds it with the operator's pubkey so the disk-booted
	// capsule comes up already adopted. Server-streams progress events;
	// the final event carries the disk-booted capsule's future identity
	// so the CLI can write a context entry that will resolve once the
	// operator removes the USB and reboots.
	Install(*InstallRequest, grpc.ServerStreamingServer[InstallProgress]) error
	mustEmbedUnimplementedInstallServiceServer()
}

// UnimplementedInstallServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstallServiceServer struct{}

func (UnimplementedInstallServiceServer) Status(context.Context, *InstallStatusRequest) (*InstallStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedInstallServiceServer) Install(*InstallRequest, grpc.ServerStreamingServer[InstallProgress]) error {
	return status.Error(codes.Unimplemented, "method Install not implemented")
}
func (UnimplementedInstallServiceServer) mustEmbedUnimplementedInstallServiceServer() {}
func (UnimplementedInstallServiceServer) testEmbeddedByValue()                        {}

// UnsafeInstallServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstallServiceServer will
// result in compilation errors.
type UnsafeInstallServiceServer interface {
	mustEmbedUnimplementedInstallServiceServer()
}

func RegisterInstallServiceServer(s grpc.ServiceRegistrar, srv InstallServiceServer) {
	// If the following call panics, it indicates UnimplementedInstallServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstallService_ServiceDesc, srv)
}

func _InstallService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstallServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstallService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstallServiceServer).Status(ctx, req.(*InstallStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InstallService_Install_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InstallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InstallServiceServer).Install(m, &grpc.GenericServerStream[InstallRequest, InstallProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InstallService_InstallServer = grpc.ServerStreamingServer[InstallProgress]

// InstallService_ServiceDesc is the grpc.ServiceDesc for InstallService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstallService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capsule.v1.InstallService",
	HandlerType: (*InstallServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _InstallService_Status_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Install",
			Handler:       _InstallService_Install_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "capsule/v1/install.proto",
}
