// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: capsule/v1/workload.proto

package capsulev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkloadService_Apply_FullMethodName    = "/capsule.v1.WorkloadService/Apply"
	WorkloadService_Get_FullMethodName      = "/capsule.v1.WorkloadService/Get"
	WorkloadService_List_FullMethodName     = "/capsule.v1.WorkloadService/List"
	WorkloadService_Delete_FullMethodName   = "/capsule.v1.WorkloadService/Delete"
	WorkloadService_Logs_FullMethodName     = "/capsule.v1.WorkloadService/Logs"
	WorkloadService_Exec_FullMethodName     = "/capsule.v1.WorkloadService/Exec"
	WorkloadService_Restart_FullMethodName  = "/capsule.v1.WorkloadService/Restart"
	WorkloadService_Stop_FullMethodName     = "/capsule.v1.WorkloadService/Stop"
	WorkloadService_Start_FullMethodName    = "/capsule.v1.WorkloadService/Start"
	WorkloadService_CopyTo_FullMethodName   = "/capsule.v1.WorkloadService/CopyTo"
	WorkloadService_CopyFrom_FullMethodName = "/capsule.v1.WorkloadService/CopyFrom"
)

// WorkloadServiceClient is the client API for WorkloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkloadService manages the declarative workload set on a capsule.
// A Workload is either a Container or a MicroVM; both share one envelope.
type WorkloadServiceClient interface {
	Apply(ctx context.Context, in *WorkloadApplyRequest, opts ...grpc.CallOption) (*WorkloadApplyResponse, error)
	Get(ctx context.Context, in *WorkloadGetRequest, opts ...grpc.CallOption) (*Workload, error)
	List(ctx context.Context, in *WorkloadListRequest, opts ...grpc.CallOption) (*WorkloadListResponse, error)
	Delete(ctx context.Context, in *WorkloadDeleteRequest, opts ...grpc.CallOption) (*WorkloadDeleteResponse, error)
	// Logs streams combined stdout+stderr from a running (or recently
	// running) workload. Stops when the client cancels, or when the
	// workload is removed and follow=false.
	Logs(ctx context.Context, in *WorkloadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkloadLogChunk], error)
	// Exec runs a one-shot process inside an already-running workload.
	// The first client message MUST be WorkloadExecClientMessage.config; subsequent
	// messages carry stdin bytes or PTY resize events. The server streams
	// stdout/stderr and finally an Exit message before closing.
	Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkloadExecClientMessage, WorkloadExecServerMessage], error)
	// Restart tears down the runtime state for a workload; the reconciler
	// recreates it on the next tick. Desired state is unchanged (still
	// RUNNING). Use for "I think it's wedged, bounce it".
	Restart(ctx context.Context, in *WorkloadRestartRequest, opts ...grpc.CallOption) (*WorkloadRestartResponse, error)
	// Stop sets the workload's desired state to STOPPED and tears down
	// its runtime state. The reconciler will NOT recreate it until Start
	// is called. Spec is preserved; survives capsule reboot.
	Stop(ctx context.Context, in *WorkloadStopRequest, opts ...grpc.CallOption) (*WorkloadStopResponse, error)
	// Start sets desired state back to RUNNING; the reconciler picks it
	// up and brings the workload back.
	Start(ctx context.Context, in *WorkloadStartRequest, opts ...grpc.CallOption) (*WorkloadStartResponse, error)
	// CopyTo streams a tar archive from the client into the workload at
	// metadata.dest_path. The first client message MUST be
	// WorkloadCopyToRequest.metadata; subsequent messages carry tar bytes.
	// The server inspects dest_path and chooses between:
	//   - "into" mode (extract entries directly under dest_path) when
	//     dest_path ends with '/' OR is an existing directory inside the
	//     workload — same as cp/scp/docker-cp behaviour.
	//   - "as" mode (extract to a temp dir, then rename the single
	//     top-level entry to dest_path) otherwise. Overwrites whatever
	//     was at dest_path.
	//
	// Workload image must include /bin/sh, mkdir, mktemp, mv, ls, wc, and
	// tar (universal in busybox/alpine/debian-derived images; not present
	// in `scratch`). Handles files, directories, and symlinks via tar's
	// normal semantics.
	CopyTo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkloadCopyToRequest, WorkloadCopyToResponse], error)
	// CopyFrom tars up src_path inside the workload and streams the
	// archive bytes back. Server runs `tar c -C <dirname(src_path)> --
	// <basename(src_path)>`. The archive contains a single top-level
	// entry (regular file or directory) named basename(src_path); the
	// client is responsible for any rename/extract behaviour.
	CopyFrom(ctx context.Context, in *WorkloadCopyFromRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkloadCopyFromChunk], error)
}

type workloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkloadServiceClient(cc grpc.ClientConnInterface) WorkloadServiceClient {
	return &workloadServiceClient{cc}
}

func (c *workloadServiceClient) Apply(ctx context.Context, in *WorkloadApplyRequest, opts ...grpc.CallOption) (*WorkloadApplyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadApplyResponse)
	err := c.cc.Invoke(ctx, WorkloadService_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) Get(ctx context.Context, in *WorkloadGetRequest, opts ...grpc.CallOption) (*Workload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Workload)
	err := c.cc.Invoke(ctx, WorkloadService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) List(ctx context.Context, in *WorkloadListRequest, opts ...grpc.CallOption) (*WorkloadListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadListResponse)
	err := c.cc.Invoke(ctx, WorkloadService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) Delete(ctx context.Context, in *WorkloadDeleteRequest, opts ...grpc.CallOption) (*WorkloadDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadDeleteResponse)
	err := c.cc.Invoke(ctx, WorkloadService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) Logs(ctx context.Context, in *WorkloadLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkloadLogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadService_ServiceDesc.Streams[0], WorkloadService_Logs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkloadLogsRequest, WorkloadLogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_LogsClient = grpc.ServerStreamingClient[WorkloadLogChunk]

func (c *workloadServiceClient) Exec(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkloadExecClientMessage, WorkloadExecServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadService_ServiceDesc.Streams[1], WorkloadService_Exec_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkloadExecClientMessage, WorkloadExecServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_ExecClient = grpc.BidiStreamingClient[WorkloadExecClientMessage, WorkloadExecServerMessage]

func (c *workloadServiceClient) Restart(ctx context.Context, in *WorkloadRestartRequest, opts ...grpc.CallOption) (*WorkloadRestartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadRestartResponse)
	err := c.cc.Invoke(ctx, WorkloadService_Restart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) Stop(ctx context.Context, in *WorkloadStopRequest, opts ...grpc.CallOption) (*WorkloadStopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadStopResponse)
	err := c.cc.Invoke(ctx, WorkloadService_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) Start(ctx context.Context, in *WorkloadStartRequest, opts ...grpc.CallOption) (*WorkloadStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkloadStartResponse)
	err := c.cc.Invoke(ctx, WorkloadService_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workloadServiceClient) CopyTo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WorkloadCopyToRequest, WorkloadCopyToResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadService_ServiceDesc.Streams[2], WorkloadService_CopyTo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkloadCopyToRequest, WorkloadCopyToResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_CopyToClient = grpc.ClientStreamingClient[WorkloadCopyToRequest, WorkloadCopyToResponse]

func (c *workloadServiceClient) CopyFrom(ctx context.Context, in *WorkloadCopyFromRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkloadCopyFromChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkloadService_ServiceDesc.Streams[3], WorkloadService_CopyFrom_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkloadCopyFromRequest, WorkloadCopyFromChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_CopyFromClient = grpc.ServerStreamingClient[WorkloadCopyFromChunk]

// WorkloadServiceServer is the server API for WorkloadService service.
// All implementations must embed UnimplementedWorkloadServiceServer
// for forward compatibility.
//
// WorkloadService manages the declarative workload set on a capsule.
// A Workload is either a Container or a MicroVM; both share one envelope.
type WorkloadServiceServer interface {
	Apply(context.Context, *WorkloadApplyRequest) (*WorkloadApplyResponse, error)
	Get(context.Context, *WorkloadGetRequest) (*Workload, error)
	List(context.Context, *WorkloadListRequest) (*WorkloadListResponse, error)
	Delete(context.Context, *WorkloadDeleteRequest) (*WorkloadDeleteResponse, error)
	// Logs streams combined stdout+stderr from a running (or recently
	// running) workload. Stops when the client cancels, or when the
	// workload is removed and follow=false.
	Logs(*WorkloadLogsRequest, grpc.ServerStreamingServer[WorkloadLogChunk]) error
	// Exec runs a one-shot process inside an already-running workload.
	// The first client message MUST be WorkloadExecClientMessage.config; subsequent
	// messages carry stdin bytes or PTY resize events. The server streams
	// stdout/stderr and finally an Exit message before closing.
	Exec(grpc.BidiStreamingServer[WorkloadExecClientMessage, WorkloadExecServerMessage]) error
	// Restart tears down the runtime state for a workload; the reconciler
	// recreates it on the next tick. Desired state is unchanged (still
	// RUNNING). Use for "I think it's wedged, bounce it".
	Restart(context.Context, *WorkloadRestartRequest) (*WorkloadRestartResponse, error)
	// Stop sets the workload's desired state to STOPPED and tears down
	// its runtime state. The reconciler will NOT recreate it until Start
	// is called. Spec is preserved; survives capsule reboot.
	Stop(context.Context, *WorkloadStopRequest) (*WorkloadStopResponse, error)
	// Start sets desired state back to RUNNING; the reconciler picks it
	// up and brings the workload back.
	Start(context.Context, *WorkloadStartRequest) (*WorkloadStartResponse, error)
	// CopyTo streams a tar archive from the client into the workload at
	// metadata.dest_path. The first client message MUST be
	// WorkloadCopyToRequest.metadata; subsequent messages carry tar bytes.
	// The server inspects dest_path and chooses between:
	//   - "into" mode (extract entries directly under dest_path) when
	//     dest_path ends with '/' OR is an existing directory inside the
	//     workload — same as cp/scp/docker-cp behaviour.
	//   - "as" mode (extract to a temp dir, then rename the single
	//     top-level entry to dest_path) otherwise. Overwrites whatever
	//     was at dest_path.
	//
	// Workload image must include /bin/sh, mkdir, mktemp, mv, ls, wc, and
	// tar (universal in busybox/alpine/debian-derived images; not present
	// in `scratch`). Handles files, directories, and symlinks via tar's
	// normal semantics.
	CopyTo(grpc.ClientStreamingServer[WorkloadCopyToRequest, WorkloadCopyToResponse]) error
	// CopyFrom tars up src_path inside the workload and streams the
	// archive bytes back. Server runs `tar c -C <dirname(src_path)> --
	// <basename(src_path)>`. The archive contains a single top-level
	// entry (regular file or directory) named basename(src_path); the
	// client is responsible for any rename/extract behaviour.
	CopyFrom(*WorkloadCopyFromRequest, grpc.ServerStreamingServer[WorkloadCopyFromChunk]) error
	mustEmbedUnimplementedWorkloadServiceServer()
}

// UnimplementedWorkloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkloadServiceServer struct{}

func (UnimplementedWorkloadServiceServer) Apply(context.Context, *WorkloadApplyRequest) (*WorkloadApplyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedWorkloadServiceServer) Get(context.Context, *WorkloadGetRequest) (*Workload, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedWorkloadServiceServer) List(context.Context, *WorkloadListRequest) (*WorkloadListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWorkloadServiceServer) Delete(context.Context, *WorkloadDeleteRequest) (*WorkloadDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWorkloadServiceServer) Logs(*WorkloadLogsRequest, grpc.ServerStreamingServer[WorkloadLogChunk]) error {
	return status.Error(codes.Unimplemented, "method Logs not implemented")
}
func (UnimplementedWorkloadServiceServer) Exec(grpc.BidiStreamingServer[WorkloadExecClientMessage, WorkloadExecServerMessage]) error {
	return status.Error(codes.Unimplemented, "method Exec not implemented")
}
func (UnimplementedWorkloadServiceServer) Restart(context.Context, *WorkloadRestartRequest) (*WorkloadRestartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Restart not implemented")
}
func (UnimplementedWorkloadServiceServer) Stop(context.Context, *WorkloadStopRequest) (*WorkloadStopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedWorkloadServiceServer) Start(context.Context, *WorkloadStartRequest) (*WorkloadStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedWorkloadServiceServer) CopyTo(grpc.ClientStreamingServer[WorkloadCopyToRequest, WorkloadCopyToResponse]) error {
	return status.Error(codes.Unimplemented, "method CopyTo not implemented")
}
func (UnimplementedWorkloadServiceServer) CopyFrom(*WorkloadCopyFromRequest, grpc.ServerStreamingServer[WorkloadCopyFromChunk]) error {
	return status.Error(codes.Unimplemented, "method CopyFrom not implemented")
}
func (UnimplementedWorkloadServiceServer) mustEmbedUnimplementedWorkloadServiceServer() {}
func (UnimplementedWorkloadServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkloadServiceServer will
// result in compilation errors.
type UnsafeWorkloadServiceServer interface {
	mustEmbedUnimplementedWorkloadServiceServer()
}

func RegisterWorkloadServiceServer(s grpc.ServiceRegistrar, srv WorkloadServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkloadService_ServiceDesc, srv)
}

func _WorkloadService_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).Apply(ctx, req.(*WorkloadApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).Get(ctx, req.(*WorkloadGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).List(ctx, req.(*WorkloadListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).Delete(ctx, req.(*WorkloadDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkloadLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadServiceServer).Logs(m, &grpc.GenericServerStream[WorkloadLogsRequest, WorkloadLogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_LogsServer = grpc.ServerStreamingServer[WorkloadLogChunk]

func _WorkloadService_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkloadServiceServer).Exec(&grpc.GenericServerStream[WorkloadExecClientMessage, WorkloadExecServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_ExecServer = grpc.BidiStreamingServer[WorkloadExecClientMessage, WorkloadExecServerMessage]

func _WorkloadService_Restart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadRestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).Restart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_Restart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).Restart(ctx, req.(*WorkloadRestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).Stop(ctx, req.(*WorkloadStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkloadStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkloadServiceServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkloadService_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkloadServiceServer).Start(ctx, req.(*WorkloadStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkloadService_CopyTo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkloadServiceServer).CopyTo(&grpc.GenericServerStream[WorkloadCopyToRequest, WorkloadCopyToResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_CopyToServer = grpc.ClientStreamingServer[WorkloadCopyToRequest, WorkloadCopyToResponse]

func _WorkloadService_CopyFrom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WorkloadCopyFromRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkloadServiceServer).CopyFrom(m, &grpc.GenericServerStream[WorkloadCopyFromRequest, WorkloadCopyFromChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkloadService_CopyFromServer = grpc.ServerStreamingServer[WorkloadCopyFromChunk]

// WorkloadService_ServiceDesc is the grpc.ServiceDesc for WorkloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "capsule.v1.WorkloadService",
	HandlerType: (*WorkloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _WorkloadService_Apply_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _WorkloadService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _WorkloadService_List_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _WorkloadService_Delete_Handler,
		},
		{
			MethodName: "Restart",
			Handler:    _WorkloadService_Restart_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _WorkloadService_Stop_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _WorkloadService_Start_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _WorkloadService_Logs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _WorkloadService_Exec_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CopyTo",
			Handler:       _WorkloadService_CopyTo_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CopyFrom",
			Handler:       _WorkloadService_CopyFrom_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "capsule/v1/workload.proto",
}
