// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: capsule/v1/workload.proto

package capsulev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DesiredState int32

const (
	DesiredState_DESIRED_STATE_UNSPECIFIED DesiredState = 0 // treated as RUNNING
	DesiredState_DESIRED_STATE_RUNNING     DesiredState = 1
	DesiredState_DESIRED_STATE_STOPPED     DesiredState = 2
	// Tombstone marker set by Service.Delete before driver.Remove. The
	// reconciler skips workloads in this state (won't restart them, won't
	// try to stop them — they're being torn down). On successful Remove,
	// the row gets deleted; on failure, the row stays at DELETING so a
	// retry of `workload delete` finishes the job without needing to
	// re-set the marker.
	DesiredState_DESIRED_STATE_DELETING DesiredState = 3
)

// Enum value maps for DesiredState.
var (
	DesiredState_name = map[int32]string{
		0: "DESIRED_STATE_UNSPECIFIED",
		1: "DESIRED_STATE_RUNNING",
		2: "DESIRED_STATE_STOPPED",
		3: "DESIRED_STATE_DELETING",
	}
	DesiredState_value = map[string]int32{
		"DESIRED_STATE_UNSPECIFIED": 0,
		"DESIRED_STATE_RUNNING":     1,
		"DESIRED_STATE_STOPPED":     2,
		"DESIRED_STATE_DELETING":    3,
	}
)

func (x DesiredState) Enum() *DesiredState {
	p := new(DesiredState)
	*p = x
	return p
}

func (x DesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_capsule_v1_workload_proto_enumTypes[0].Descriptor()
}

func (DesiredState) Type() protoreflect.EnumType {
	return &file_capsule_v1_workload_proto_enumTypes[0]
}

func (x DesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesiredState.Descriptor instead.
func (DesiredState) EnumDescriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{0}
}

type WorkloadKind int32

const (
	WorkloadKind_WORKLOAD_KIND_UNSPECIFIED WorkloadKind = 0
	WorkloadKind_WORKLOAD_KIND_CONTAINER   WorkloadKind = 1
	WorkloadKind_WORKLOAD_KIND_MICRO_VM    WorkloadKind = 2
)

// Enum value maps for WorkloadKind.
var (
	WorkloadKind_name = map[int32]string{
		0: "WORKLOAD_KIND_UNSPECIFIED",
		1: "WORKLOAD_KIND_CONTAINER",
		2: "WORKLOAD_KIND_MICRO_VM",
	}
	WorkloadKind_value = map[string]int32{
		"WORKLOAD_KIND_UNSPECIFIED": 0,
		"WORKLOAD_KIND_CONTAINER":   1,
		"WORKLOAD_KIND_MICRO_VM":    2,
	}
)

func (x WorkloadKind) Enum() *WorkloadKind {
	p := new(WorkloadKind)
	*p = x
	return p
}

func (x WorkloadKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadKind) Descriptor() protoreflect.EnumDescriptor {
	return file_capsule_v1_workload_proto_enumTypes[1].Descriptor()
}

func (WorkloadKind) Type() protoreflect.EnumType {
	return &file_capsule_v1_workload_proto_enumTypes[1]
}

func (x WorkloadKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadKind.Descriptor instead.
func (WorkloadKind) EnumDescriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{1}
}

type WorkloadPhase int32

const (
	WorkloadPhase_WORKLOAD_PHASE_UNSPECIFIED WorkloadPhase = 0
	WorkloadPhase_WORKLOAD_PHASE_PENDING     WorkloadPhase = 1
	WorkloadPhase_WORKLOAD_PHASE_RUNNING     WorkloadPhase = 2
	WorkloadPhase_WORKLOAD_PHASE_FAILED      WorkloadPhase = 3
	WorkloadPhase_WORKLOAD_PHASE_STOPPED     WorkloadPhase = 4
)

// Enum value maps for WorkloadPhase.
var (
	WorkloadPhase_name = map[int32]string{
		0: "WORKLOAD_PHASE_UNSPECIFIED",
		1: "WORKLOAD_PHASE_PENDING",
		2: "WORKLOAD_PHASE_RUNNING",
		3: "WORKLOAD_PHASE_FAILED",
		4: "WORKLOAD_PHASE_STOPPED",
	}
	WorkloadPhase_value = map[string]int32{
		"WORKLOAD_PHASE_UNSPECIFIED": 0,
		"WORKLOAD_PHASE_PENDING":     1,
		"WORKLOAD_PHASE_RUNNING":     2,
		"WORKLOAD_PHASE_FAILED":      3,
		"WORKLOAD_PHASE_STOPPED":     4,
	}
)

func (x WorkloadPhase) Enum() *WorkloadPhase {
	p := new(WorkloadPhase)
	*p = x
	return p
}

func (x WorkloadPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_capsule_v1_workload_proto_enumTypes[2].Descriptor()
}

func (WorkloadPhase) Type() protoreflect.EnumType {
	return &file_capsule_v1_workload_proto_enumTypes[2]
}

func (x WorkloadPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadPhase.Descriptor instead.
func (WorkloadPhase) EnumDescriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{2}
}

type NetworkMode int32

const (
	// Default: private network namespace with only loopback available.
	NetworkMode_NETWORK_MODE_UNSPECIFIED NetworkMode = 0
	// Share the host's network namespace. Container binds directly to the
	// capsule's interfaces. No isolation between container and host.
	NetworkMode_NETWORK_MODE_HOST NetworkMode = 1
	// veth pair into a host bridge. Reserved for Phase 2.5 — not yet
	// implemented by the runtime driver.
	NetworkMode_NETWORK_MODE_BRIDGE NetworkMode = 2
)

// Enum value maps for NetworkMode.
var (
	NetworkMode_name = map[int32]string{
		0: "NETWORK_MODE_UNSPECIFIED",
		1: "NETWORK_MODE_HOST",
		2: "NETWORK_MODE_BRIDGE",
	}
	NetworkMode_value = map[string]int32{
		"NETWORK_MODE_UNSPECIFIED": 0,
		"NETWORK_MODE_HOST":        1,
		"NETWORK_MODE_BRIDGE":      2,
	}
)

func (x NetworkMode) Enum() *NetworkMode {
	p := new(NetworkMode)
	*p = x
	return p
}

func (x NetworkMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkMode) Descriptor() protoreflect.EnumDescriptor {
	return file_capsule_v1_workload_proto_enumTypes[3].Descriptor()
}

func (NetworkMode) Type() protoreflect.EnumType {
	return &file_capsule_v1_workload_proto_enumTypes[3]
}

func (x NetworkMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkMode.Descriptor instead.
func (NetworkMode) EnumDescriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{3}
}

type MicroVMBackend int32

const (
	MicroVMBackend_MICRO_VM_BACKEND_UNSPECIFIED MicroVMBackend = 0
	MicroVMBackend_MICRO_VM_BACKEND_FIRECRACKER MicroVMBackend = 1
	// SMOLVM is reserved for a future backend driver.
	MicroVMBackend_MICRO_VM_BACKEND_SMOLVM MicroVMBackend = 2
)

// Enum value maps for MicroVMBackend.
var (
	MicroVMBackend_name = map[int32]string{
		0: "MICRO_VM_BACKEND_UNSPECIFIED",
		1: "MICRO_VM_BACKEND_FIRECRACKER",
		2: "MICRO_VM_BACKEND_SMOLVM",
	}
	MicroVMBackend_value = map[string]int32{
		"MICRO_VM_BACKEND_UNSPECIFIED": 0,
		"MICRO_VM_BACKEND_FIRECRACKER": 1,
		"MICRO_VM_BACKEND_SMOLVM":      2,
	}
)

func (x MicroVMBackend) Enum() *MicroVMBackend {
	p := new(MicroVMBackend)
	*p = x
	return p
}

func (x MicroVMBackend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MicroVMBackend) Descriptor() protoreflect.EnumDescriptor {
	return file_capsule_v1_workload_proto_enumTypes[4].Descriptor()
}

func (MicroVMBackend) Type() protoreflect.EnumType {
	return &file_capsule_v1_workload_proto_enumTypes[4]
}

func (x MicroVMBackend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MicroVMBackend.Descriptor instead.
func (MicroVMBackend) EnumDescriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{4}
}

type LogSource int32

const (
	LogSource_LOG_SOURCE_UNSPECIFIED LogSource = 0 // treated as PAYLOAD
	LogSource_LOG_SOURCE_PAYLOAD     LogSource = 1
	LogSource_LOG_SOURCE_SERIAL      LogSource = 2
)

// Enum value maps for LogSource.
var (
	LogSource_name = map[int32]string{
		0: "LOG_SOURCE_UNSPECIFIED",
		1: "LOG_SOURCE_PAYLOAD",
		2: "LOG_SOURCE_SERIAL",
	}
	LogSource_value = map[string]int32{
		"LOG_SOURCE_UNSPECIFIED": 0,
		"LOG_SOURCE_PAYLOAD":     1,
		"LOG_SOURCE_SERIAL":      2,
	}
)

func (x LogSource) Enum() *LogSource {
	p := new(LogSource)
	*p = x
	return p
}

func (x LogSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogSource) Descriptor() protoreflect.EnumDescriptor {
	return file_capsule_v1_workload_proto_enumTypes[5].Descriptor()
}

func (LogSource) Type() protoreflect.EnumType {
	return &file_capsule_v1_workload_proto_enumTypes[5]
}

func (x LogSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogSource.Descriptor instead.
func (LogSource) EnumDescriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{5}
}

type Workload struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind      WorkloadKind           `protobuf:"varint,2,opt,name=kind,proto3,enum=capsule.v1.WorkloadKind" json:"kind,omitempty"`
	Container *ContainerSpec         `protobuf:"bytes,3,opt,name=container,proto3" json:"container,omitempty"`
	MicroVm   *MicroVMSpec           `protobuf:"bytes,4,opt,name=micro_vm,json=microVm,proto3" json:"micro_vm,omitempty"`
	Status    *WorkloadStatus        `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// Desired state. UNSPECIFIED is treated as RUNNING (default for
	// freshly-applied workloads). Set to STOPPED via the Stop RPC; that
	// tells the reconciler to tear down the workload and leave it down
	// until Start. Preserved across capsule reboots.
	DesiredState  DesiredState `protobuf:"varint,6,opt,name=desired_state,json=desiredState,proto3,enum=capsule.v1.DesiredState" json:"desired_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_capsule_v1_workload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{0}
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetKind() WorkloadKind {
	if x != nil {
		return x.Kind
	}
	return WorkloadKind_WORKLOAD_KIND_UNSPECIFIED
}

func (x *Workload) GetContainer() *ContainerSpec {
	if x != nil {
		return x.Container
	}
	return nil
}

func (x *Workload) GetMicroVm() *MicroVMSpec {
	if x != nil {
		return x.MicroVm
	}
	return nil
}

func (x *Workload) GetStatus() *WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *Workload) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

type ContainerSpec struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Image   string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Args    []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env     map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Mounts  []*VolumeMount         `protobuf:"bytes,5,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Network mode. UNSPECIFIED defaults to a private netns with only
	// loopback (the container can talk to itself and nothing else).
	NetworkMode NetworkMode `protobuf:"varint,6,opt,name=network_mode,json=networkMode,proto3,enum=capsule.v1.NetworkMode" json:"network_mode,omitempty"`
	// Port mappings. Only meaningful when network_mode == BRIDGE.
	Ports []*PortMapping `protobuf:"bytes,7,rep,name=ports,proto3" json:"ports,omitempty"`
	// Run with all caps + raw access to /dev + relaxed seccomp/AppArmor.
	// Equivalent to docker run --privileged.
	Privileged bool `protobuf:"varint,8,opt,name=privileged,proto3" json:"privileged,omitempty"`
	// Share the host PID namespace — process list inside the container
	// sees capsuled, containerd, runc, firecracker, etc.
	HostPid bool `protobuf:"varint,9,opt,name=host_pid,json=hostPid,proto3" json:"host_pid,omitempty"`
	// Share the host mount namespace. Bind-mounts done inside the container
	// become visible to the host (and vice versa). Use sparingly.
	HostMount bool `protobuf:"varint,10,opt,name=host_mount,json=hostMount,proto3" json:"host_mount,omitempty"`
	// Share the host IPC namespace.
	HostIpc bool `protobuf:"varint,11,opt,name=host_ipc,json=hostIpc,proto3" json:"host_ipc,omitempty"`
	// Bind-mount these absolute paths from the host into the container at
	// the same path. Read-write. Used by capsule debug to expose /perm,
	// /sys, /dev, /run/capsule, /usr/sbin (so host's lvs/iptables/etc.
	// work without being shipped in the debug image).
	HostBindPaths []string `protobuf:"bytes,12,rep,name=host_bind_paths,json=hostBindPaths,proto3" json:"host_bind_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_capsule_v1_workload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{1}
}

func (x *ContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerSpec) GetMounts() []*VolumeMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *ContainerSpec) GetNetworkMode() NetworkMode {
	if x != nil {
		return x.NetworkMode
	}
	return NetworkMode_NETWORK_MODE_UNSPECIFIED
}

func (x *ContainerSpec) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSpec) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

func (x *ContainerSpec) GetHostPid() bool {
	if x != nil {
		return x.HostPid
	}
	return false
}

func (x *ContainerSpec) GetHostMount() bool {
	if x != nil {
		return x.HostMount
	}
	return false
}

func (x *ContainerSpec) GetHostIpc() bool {
	if x != nil {
		return x.HostIpc
	}
	return false
}

func (x *ContainerSpec) GetHostBindPaths() []string {
	if x != nil {
		return x.HostBindPaths
	}
	return nil
}

type PortMapping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Port inside the container.
	ContainerPort uint32 `protobuf:"varint,1,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	// Port on the host/capsule. 0 means auto-allocate (not yet supported).
	HostPort uint32 `protobuf:"varint,2,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	// "tcp" or "udp". Empty defaults to "tcp".
	Protocol      string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_capsule_v1_workload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{2}
}

func (x *PortMapping) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortMapping) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type MicroVMSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ---- Image-mode (smolvm-style): easy path ---------------------------
	// OCI image reference (same shape as ContainerSpec.image). When set,
	// capsule pulls the image, builds an ext4 rootfs from its layers, injects
	// capsuled's guest-init as /sbin/init, and boots a Firecracker microVM
	// using the capsule's bundled shared kernel (/usr/share/capsule/vmlinux).
	// Mutually exclusive with kernel_path/rootfs_path.
	Image string `protobuf:"bytes,8,opt,name=image,proto3" json:"image,omitempty"`
	// Override the entrypoint declared in the image (like docker --entrypoint).
	Command []string `protobuf:"bytes,9,rep,name=command,proto3" json:"command,omitempty"`
	// Args appended to the entrypoint (like docker CMD).
	Args []string `protobuf:"bytes,10,rep,name=args,proto3" json:"args,omitempty"`
	// Env vars merged with the image's defaults.
	Env map[string]string `protobuf:"bytes,11,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ---- BYO-kernel mode: advanced / custom -----------------------------
	// Absolute path on the capsule to a raw Linux kernel image (vmlinux).
	// Only consulted when `image` is empty.
	KernelPath string `protobuf:"bytes,1,opt,name=kernel_path,json=kernelPath,proto3" json:"kernel_path,omitempty"`
	// Absolute path to an ext4 root filesystem image. Only consulted when
	// `image` is empty.
	RootfsPath string `protobuf:"bytes,2,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"`
	// ---- Common ---------------------------------------------------------
	// Number of vCPUs. Zero defaults to 1.
	Vcpus uint32 `protobuf:"varint,3,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	// Guest memory size in MiB. Zero defaults to 256.
	MemoryMib uint32 `protobuf:"varint,4,opt,name=memory_mib,json=memoryMib,proto3" json:"memory_mib,omitempty"`
	// Additional block devices (volumes attached as /dev/vdN to the guest).
	Mounts []*VolumeMount `protobuf:"bytes,5,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Extra kernel cmdline args appended to Capsule's defaults.
	KernelCmdlineExtra string `protobuf:"bytes,6,opt,name=kernel_cmdline_extra,json=kernelCmdlineExtra,proto3" json:"kernel_cmdline_extra,omitempty"`
	// Backend to run the VM in. UNSPECIFIED defaults to FIRECRACKER.
	Backend MicroVMBackend `protobuf:"varint,7,opt,name=backend,proto3,enum=capsule.v1.MicroVMBackend" json:"backend,omitempty"`
	// Port mappings. Each entry DNATs <host_port> on the capsule to
	// <container_port> on this VM's internal IP (br0 side).
	Ports         []*PortMapping `protobuf:"bytes,12,rep,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MicroVMSpec) Reset() {
	*x = MicroVMSpec{}
	mi := &file_capsule_v1_workload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MicroVMSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MicroVMSpec) ProtoMessage() {}

func (x *MicroVMSpec) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MicroVMSpec.ProtoReflect.Descriptor instead.
func (*MicroVMSpec) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{3}
}

func (x *MicroVMSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *MicroVMSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *MicroVMSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *MicroVMSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *MicroVMSpec) GetKernelPath() string {
	if x != nil {
		return x.KernelPath
	}
	return ""
}

func (x *MicroVMSpec) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

func (x *MicroVMSpec) GetVcpus() uint32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *MicroVMSpec) GetMemoryMib() uint32 {
	if x != nil {
		return x.MemoryMib
	}
	return 0
}

func (x *MicroVMSpec) GetMounts() []*VolumeMount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *MicroVMSpec) GetKernelCmdlineExtra() string {
	if x != nil {
		return x.KernelCmdlineExtra
	}
	return ""
}

func (x *MicroVMSpec) GetBackend() MicroVMBackend {
	if x != nil {
		return x.Backend
	}
	return MicroVMBackend_MICRO_VM_BACKEND_UNSPECIFIED
}

func (x *MicroVMSpec) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeName    string                 `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_capsule_v1_workload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeMount) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *VolumeMount) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type WorkloadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         WorkloadPhase          `protobuf:"varint,1,opt,name=phase,proto3,enum=capsule.v1.WorkloadPhase" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RestartCount  uint32                 `protobuf:"varint,3,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_capsule_v1_workload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{5}
}

func (x *WorkloadStatus) GetPhase() WorkloadPhase {
	if x != nil {
		return x.Phase
	}
	return WorkloadPhase_WORKLOAD_PHASE_UNSPECIFIED
}

func (x *WorkloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadStatus) GetRestartCount() uint32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

type WorkloadApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadApplyRequest) Reset() {
	*x = WorkloadApplyRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadApplyRequest) ProtoMessage() {}

func (x *WorkloadApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadApplyRequest.ProtoReflect.Descriptor instead.
func (*WorkloadApplyRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{6}
}

func (x *WorkloadApplyRequest) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type WorkloadApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *Workload              `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadApplyResponse) Reset() {
	*x = WorkloadApplyResponse{}
	mi := &file_capsule_v1_workload_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadApplyResponse) ProtoMessage() {}

func (x *WorkloadApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadApplyResponse.ProtoReflect.Descriptor instead.
func (*WorkloadApplyResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{7}
}

func (x *WorkloadApplyResponse) GetWorkload() *Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

type WorkloadGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadGetRequest) Reset() {
	*x = WorkloadGetRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadGetRequest) ProtoMessage() {}

func (x *WorkloadGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadGetRequest.ProtoReflect.Descriptor instead.
func (*WorkloadGetRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{8}
}

func (x *WorkloadGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkloadListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadListRequest) Reset() {
	*x = WorkloadListRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadListRequest) ProtoMessage() {}

func (x *WorkloadListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadListRequest.ProtoReflect.Descriptor instead.
func (*WorkloadListRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{9}
}

type WorkloadListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*Workload            `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadListResponse) Reset() {
	*x = WorkloadListResponse{}
	mi := &file_capsule_v1_workload_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadListResponse) ProtoMessage() {}

func (x *WorkloadListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadListResponse.ProtoReflect.Descriptor instead.
func (*WorkloadListResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{10}
}

func (x *WorkloadListResponse) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type WorkloadDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadDeleteRequest) Reset() {
	*x = WorkloadDeleteRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadDeleteRequest) ProtoMessage() {}

func (x *WorkloadDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadDeleteRequest.ProtoReflect.Descriptor instead.
func (*WorkloadDeleteRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{11}
}

func (x *WorkloadDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkloadDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadDeleteResponse) Reset() {
	*x = WorkloadDeleteResponse{}
	mi := &file_capsule_v1_workload_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadDeleteResponse) ProtoMessage() {}

func (x *WorkloadDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadDeleteResponse.ProtoReflect.Descriptor instead.
func (*WorkloadDeleteResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{12}
}

type WorkloadLogsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// follow keeps the stream open and emits new data as it arrives.
	Follow bool `protobuf:"varint,2,opt,name=follow,proto3" json:"follow,omitempty"`
	// tail_lines returns only the last N lines from the existing log before
	// streaming any new data. 0 means "from the start of the file".
	TailLines int32 `protobuf:"varint,3,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	// source selects which log to stream. PAYLOAD is the application's
	// combined stdout+stderr (default). SERIAL is the VM's serial console
	// output — kernel boot, capsule-guest, Firecracker. Only valid for MicroVM
	// workloads.
	Source        LogSource `protobuf:"varint,4,opt,name=source,proto3,enum=capsule.v1.LogSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadLogsRequest) Reset() {
	*x = WorkloadLogsRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadLogsRequest) ProtoMessage() {}

func (x *WorkloadLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadLogsRequest.ProtoReflect.Descriptor instead.
func (*WorkloadLogsRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{13}
}

func (x *WorkloadLogsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *WorkloadLogsRequest) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *WorkloadLogsRequest) GetSource() LogSource {
	if x != nil {
		return x.Source
	}
	return LogSource_LOG_SOURCE_UNSPECIFIED
}

type WorkloadLogChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is a raw byte slice from the combined stdout+stderr log. Line
	// framing is preserved but not guaranteed — clients should treat this
	// as a byte stream.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadLogChunk) Reset() {
	*x = WorkloadLogChunk{}
	mi := &file_capsule_v1_workload_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadLogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadLogChunk) ProtoMessage() {}

func (x *WorkloadLogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadLogChunk.ProtoReflect.Descriptor instead.
func (*WorkloadLogChunk) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{14}
}

func (x *WorkloadLogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkloadExecClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkloadExecClientMessage_Config
	//	*WorkloadExecClientMessage_Stdin
	//	*WorkloadExecClientMessage_Resize
	Payload       isWorkloadExecClientMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadExecClientMessage) Reset() {
	*x = WorkloadExecClientMessage{}
	mi := &file_capsule_v1_workload_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadExecClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadExecClientMessage) ProtoMessage() {}

func (x *WorkloadExecClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadExecClientMessage.ProtoReflect.Descriptor instead.
func (*WorkloadExecClientMessage) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{15}
}

func (x *WorkloadExecClientMessage) GetPayload() isWorkloadExecClientMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkloadExecClientMessage) GetConfig() *WorkloadExecConfig {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadExecClientMessage_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *WorkloadExecClientMessage) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadExecClientMessage_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *WorkloadExecClientMessage) GetResize() *WorkloadExecResize {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadExecClientMessage_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isWorkloadExecClientMessage_Payload interface {
	isWorkloadExecClientMessage_Payload()
}

type WorkloadExecClientMessage_Config struct {
	Config *WorkloadExecConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type WorkloadExecClientMessage_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type WorkloadExecClientMessage_Resize struct {
	Resize *WorkloadExecResize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

func (*WorkloadExecClientMessage_Config) isWorkloadExecClientMessage_Payload() {}

func (*WorkloadExecClientMessage_Stdin) isWorkloadExecClientMessage_Payload() {}

func (*WorkloadExecClientMessage_Resize) isWorkloadExecClientMessage_Payload() {}

type WorkloadExecConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the running workload to exec inside.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Command to run (argv). Required, must have at least one element.
	Command []string `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	// If true, allocate a PTY; server will send stdout only (no stderr
	// split) and expect resize events.
	Tty bool `protobuf:"varint,3,opt,name=tty,proto3" json:"tty,omitempty"`
	// Extra environment variables for the exec'd process. Merged with the
	// container's default env.
	Env           map[string]string `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadExecConfig) Reset() {
	*x = WorkloadExecConfig{}
	mi := &file_capsule_v1_workload_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadExecConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadExecConfig) ProtoMessage() {}

func (x *WorkloadExecConfig) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadExecConfig.ProtoReflect.Descriptor instead.
func (*WorkloadExecConfig) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{16}
}

func (x *WorkloadExecConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadExecConfig) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WorkloadExecConfig) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *WorkloadExecConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type WorkloadExecResize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadExecResize) Reset() {
	*x = WorkloadExecResize{}
	mi := &file_capsule_v1_workload_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadExecResize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadExecResize) ProtoMessage() {}

func (x *WorkloadExecResize) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadExecResize.ProtoReflect.Descriptor instead.
func (*WorkloadExecResize) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{17}
}

func (x *WorkloadExecResize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *WorkloadExecResize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type WorkloadExecServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkloadExecServerMessage_Stdout
	//	*WorkloadExecServerMessage_Stderr
	//	*WorkloadExecServerMessage_Exit
	Payload       isWorkloadExecServerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadExecServerMessage) Reset() {
	*x = WorkloadExecServerMessage{}
	mi := &file_capsule_v1_workload_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadExecServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadExecServerMessage) ProtoMessage() {}

func (x *WorkloadExecServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadExecServerMessage.ProtoReflect.Descriptor instead.
func (*WorkloadExecServerMessage) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{18}
}

func (x *WorkloadExecServerMessage) GetPayload() isWorkloadExecServerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkloadExecServerMessage) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadExecServerMessage_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *WorkloadExecServerMessage) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadExecServerMessage_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *WorkloadExecServerMessage) GetExit() *WorkloadExecExit {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadExecServerMessage_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isWorkloadExecServerMessage_Payload interface {
	isWorkloadExecServerMessage_Payload()
}

type WorkloadExecServerMessage_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type WorkloadExecServerMessage_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type WorkloadExecServerMessage_Exit struct {
	Exit *WorkloadExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*WorkloadExecServerMessage_Stdout) isWorkloadExecServerMessage_Payload() {}

func (*WorkloadExecServerMessage_Stderr) isWorkloadExecServerMessage_Payload() {}

func (*WorkloadExecServerMessage_Exit) isWorkloadExecServerMessage_Payload() {}

type WorkloadExecExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadExecExit) Reset() {
	*x = WorkloadExecExit{}
	mi := &file_capsule_v1_workload_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadExecExit) ProtoMessage() {}

func (x *WorkloadExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadExecExit.ProtoReflect.Descriptor instead.
func (*WorkloadExecExit) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{19}
}

func (x *WorkloadExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type WorkloadRestartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRestartRequest) Reset() {
	*x = WorkloadRestartRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRestartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRestartRequest) ProtoMessage() {}

func (x *WorkloadRestartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRestartRequest.ProtoReflect.Descriptor instead.
func (*WorkloadRestartRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{20}
}

func (x *WorkloadRestartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkloadRestartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadRestartResponse) Reset() {
	*x = WorkloadRestartResponse{}
	mi := &file_capsule_v1_workload_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadRestartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadRestartResponse) ProtoMessage() {}

func (x *WorkloadRestartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadRestartResponse.ProtoReflect.Descriptor instead.
func (*WorkloadRestartResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{21}
}

type WorkloadStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStopRequest) Reset() {
	*x = WorkloadStopRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStopRequest) ProtoMessage() {}

func (x *WorkloadStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStopRequest.ProtoReflect.Descriptor instead.
func (*WorkloadStopRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{22}
}

func (x *WorkloadStopRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkloadStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStopResponse) Reset() {
	*x = WorkloadStopResponse{}
	mi := &file_capsule_v1_workload_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStopResponse) ProtoMessage() {}

func (x *WorkloadStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStopResponse.ProtoReflect.Descriptor instead.
func (*WorkloadStopResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{23}
}

type WorkloadStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStartRequest) Reset() {
	*x = WorkloadStartRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStartRequest) ProtoMessage() {}

func (x *WorkloadStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStartRequest.ProtoReflect.Descriptor instead.
func (*WorkloadStartRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{24}
}

func (x *WorkloadStartRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkloadStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStartResponse) Reset() {
	*x = WorkloadStartResponse{}
	mi := &file_capsule_v1_workload_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStartResponse) ProtoMessage() {}

func (x *WorkloadStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStartResponse.ProtoReflect.Descriptor instead.
func (*WorkloadStartResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{25}
}

type WorkloadCopyToRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*WorkloadCopyToRequest_Metadata
	//	*WorkloadCopyToRequest_Chunk
	Payload       isWorkloadCopyToRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCopyToRequest) Reset() {
	*x = WorkloadCopyToRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCopyToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCopyToRequest) ProtoMessage() {}

func (x *WorkloadCopyToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCopyToRequest.ProtoReflect.Descriptor instead.
func (*WorkloadCopyToRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{26}
}

func (x *WorkloadCopyToRequest) GetPayload() isWorkloadCopyToRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WorkloadCopyToRequest) GetMetadata() *WorkloadCopyToMetadata {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadCopyToRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *WorkloadCopyToRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*WorkloadCopyToRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isWorkloadCopyToRequest_Payload interface {
	isWorkloadCopyToRequest_Payload()
}

type WorkloadCopyToRequest_Metadata struct {
	Metadata *WorkloadCopyToMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type WorkloadCopyToRequest_Chunk struct {
	// Raw tar archive bytes. Stream as many as needed; close-send when done.
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*WorkloadCopyToRequest_Metadata) isWorkloadCopyToRequest_Payload() {}

func (*WorkloadCopyToRequest_Chunk) isWorkloadCopyToRequest_Payload() {}

type WorkloadCopyToMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the running workload to copy into.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Absolute path inside the workload to copy to. A trailing '/' OR the
	// path being an existing directory means "extract entries directly
	// beneath this path". Anything else means "the single top-level
	// archive entry is renamed to this path". Parent directories are
	// created with `mkdir -p` as needed.
	DestPath      string `protobuf:"bytes,2,opt,name=dest_path,json=destPath,proto3" json:"dest_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCopyToMetadata) Reset() {
	*x = WorkloadCopyToMetadata{}
	mi := &file_capsule_v1_workload_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCopyToMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCopyToMetadata) ProtoMessage() {}

func (x *WorkloadCopyToMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCopyToMetadata.ProtoReflect.Descriptor instead.
func (*WorkloadCopyToMetadata) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{27}
}

func (x *WorkloadCopyToMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadCopyToMetadata) GetDestPath() string {
	if x != nil {
		return x.DestPath
	}
	return ""
}

type WorkloadCopyToResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total tar bytes received from the client.
	BytesReceived int64 `protobuf:"varint,1,opt,name=bytes_received,json=bytesReceived,proto3" json:"bytes_received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCopyToResponse) Reset() {
	*x = WorkloadCopyToResponse{}
	mi := &file_capsule_v1_workload_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCopyToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCopyToResponse) ProtoMessage() {}

func (x *WorkloadCopyToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCopyToResponse.ProtoReflect.Descriptor instead.
func (*WorkloadCopyToResponse) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{28}
}

func (x *WorkloadCopyToResponse) GetBytesReceived() int64 {
	if x != nil {
		return x.BytesReceived
	}
	return 0
}

type WorkloadCopyFromRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the running workload to copy from.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Absolute path inside the workload to archive. May refer to a
	// regular file or a directory; tar handles either.
	SrcPath       string `protobuf:"bytes,2,opt,name=src_path,json=srcPath,proto3" json:"src_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCopyFromRequest) Reset() {
	*x = WorkloadCopyFromRequest{}
	mi := &file_capsule_v1_workload_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCopyFromRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCopyFromRequest) ProtoMessage() {}

func (x *WorkloadCopyFromRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCopyFromRequest.ProtoReflect.Descriptor instead.
func (*WorkloadCopyFromRequest) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{29}
}

func (x *WorkloadCopyFromRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkloadCopyFromRequest) GetSrcPath() string {
	if x != nil {
		return x.SrcPath
	}
	return ""
}

type WorkloadCopyFromChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw tar archive bytes.
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCopyFromChunk) Reset() {
	*x = WorkloadCopyFromChunk{}
	mi := &file_capsule_v1_workload_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCopyFromChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCopyFromChunk) ProtoMessage() {}

func (x *WorkloadCopyFromChunk) ProtoReflect() protoreflect.Message {
	mi := &file_capsule_v1_workload_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCopyFromChunk.ProtoReflect.Descriptor instead.
func (*WorkloadCopyFromChunk) Descriptor() ([]byte, []int) {
	return file_capsule_v1_workload_proto_rawDescGZIP(), []int{30}
}

func (x *WorkloadCopyFromChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_capsule_v1_workload_proto protoreflect.FileDescriptor

const file_capsule_v1_workload_proto_rawDesc = "" +
	"\n" +
	"\x19capsule/v1/workload.proto\x12\n" +
	"capsule.v1\"\xac\x02\n" +
	"\bWorkload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x18.capsule.v1.WorkloadKindR\x04kind\x127\n" +
	"\tcontainer\x18\x03 \x01(\v2\x19.capsule.v1.ContainerSpecR\tcontainer\x122\n" +
	"\bmicro_vm\x18\x04 \x01(\v2\x17.capsule.v1.MicroVMSpecR\amicroVm\x122\n" +
	"\x06status\x18\x05 \x01(\v2\x1a.capsule.v1.WorkloadStatusR\x06status\x12=\n" +
	"\rdesired_state\x18\x06 \x01(\x0e2\x18.capsule.v1.DesiredStateR\fdesiredState\"\xfa\x03\n" +
	"\rContainerSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x124\n" +
	"\x03env\x18\x04 \x03(\v2\".capsule.v1.ContainerSpec.EnvEntryR\x03env\x12/\n" +
	"\x06mounts\x18\x05 \x03(\v2\x17.capsule.v1.VolumeMountR\x06mounts\x12:\n" +
	"\fnetwork_mode\x18\x06 \x01(\x0e2\x17.capsule.v1.NetworkModeR\vnetworkMode\x12-\n" +
	"\x05ports\x18\a \x03(\v2\x17.capsule.v1.PortMappingR\x05ports\x12\x1e\n" +
	"\n" +
	"privileged\x18\b \x01(\bR\n" +
	"privileged\x12\x19\n" +
	"\bhost_pid\x18\t \x01(\bR\ahostPid\x12\x1d\n" +
	"\n" +
	"host_mount\x18\n" +
	" \x01(\bR\thostMount\x12\x19\n" +
	"\bhost_ipc\x18\v \x01(\bR\ahostIpc\x12&\n" +
	"\x0fhost_bind_paths\x18\f \x03(\tR\rhostBindPaths\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\vPortMapping\x12%\n" +
	"\x0econtainer_port\x18\x01 \x01(\rR\rcontainerPort\x12\x1b\n" +
	"\thost_port\x18\x02 \x01(\rR\bhostPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xfc\x03\n" +
	"\vMicroVMSpec\x12\x14\n" +
	"\x05image\x18\b \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\t \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\n" +
	" \x03(\tR\x04args\x122\n" +
	"\x03env\x18\v \x03(\v2 .capsule.v1.MicroVMSpec.EnvEntryR\x03env\x12\x1f\n" +
	"\vkernel_path\x18\x01 \x01(\tR\n" +
	"kernelPath\x12\x1f\n" +
	"\vrootfs_path\x18\x02 \x01(\tR\n" +
	"rootfsPath\x12\x14\n" +
	"\x05vcpus\x18\x03 \x01(\rR\x05vcpus\x12\x1d\n" +
	"\n" +
	"memory_mib\x18\x04 \x01(\rR\tmemoryMib\x12/\n" +
	"\x06mounts\x18\x05 \x03(\v2\x17.capsule.v1.VolumeMountR\x06mounts\x120\n" +
	"\x14kernel_cmdline_extra\x18\x06 \x01(\tR\x12kernelCmdlineExtra\x124\n" +
	"\abackend\x18\a \x01(\x0e2\x1a.capsule.v1.MicroVMBackendR\abackend\x12-\n" +
	"\x05ports\x18\f \x03(\v2\x17.capsule.v1.PortMappingR\x05ports\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\vVolumeMount\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"\x80\x01\n" +
	"\x0eWorkloadStatus\x12/\n" +
	"\x05phase\x18\x01 \x01(\x0e2\x19.capsule.v1.WorkloadPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rrestart_count\x18\x03 \x01(\rR\frestartCount\"H\n" +
	"\x14WorkloadApplyRequest\x120\n" +
	"\bworkload\x18\x01 \x01(\v2\x14.capsule.v1.WorkloadR\bworkload\"I\n" +
	"\x15WorkloadApplyResponse\x120\n" +
	"\bworkload\x18\x01 \x01(\v2\x14.capsule.v1.WorkloadR\bworkload\"(\n" +
	"\x12WorkloadGetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13WorkloadListRequest\"J\n" +
	"\x14WorkloadListResponse\x122\n" +
	"\tworkloads\x18\x01 \x03(\v2\x14.capsule.v1.WorkloadR\tworkloads\"+\n" +
	"\x15WorkloadDeleteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x18\n" +
	"\x16WorkloadDeleteResponse\"\x8f\x01\n" +
	"\x13WorkloadLogsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06follow\x18\x02 \x01(\bR\x06follow\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x03 \x01(\x05R\ttailLines\x12-\n" +
	"\x06source\x18\x04 \x01(\x0e2\x15.capsule.v1.LogSourceR\x06source\"&\n" +
	"\x10WorkloadLogChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xb2\x01\n" +
	"\x19WorkloadExecClientMessage\x128\n" +
	"\x06config\x18\x01 \x01(\v2\x1e.capsule.v1.WorkloadExecConfigH\x00R\x06config\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x128\n" +
	"\x06resize\x18\x03 \x01(\v2\x1e.capsule.v1.WorkloadExecResizeH\x00R\x06resizeB\t\n" +
	"\apayload\"\xc7\x01\n" +
	"\x12WorkloadExecConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\x03 \x01(\bR\x03tty\x129\n" +
	"\x03env\x18\x04 \x03(\v2'.capsule.v1.WorkloadExecConfig.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x12WorkloadExecResize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x8e\x01\n" +
	"\x19WorkloadExecServerMessage\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x122\n" +
	"\x04exit\x18\x03 \x01(\v2\x1c.capsule.v1.WorkloadExecExitH\x00R\x04exitB\t\n" +
	"\apayload\"/\n" +
	"\x10WorkloadExecExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\",\n" +
	"\x16WorkloadRestartRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17WorkloadRestartResponse\")\n" +
	"\x13WorkloadStopRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14WorkloadStopResponse\"*\n" +
	"\x14WorkloadStartRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15WorkloadStartResponse\"|\n" +
	"\x15WorkloadCopyToRequest\x12@\n" +
	"\bmetadata\x18\x01 \x01(\v2\".capsule.v1.WorkloadCopyToMetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\t\n" +
	"\apayload\"I\n" +
	"\x16WorkloadCopyToMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tdest_path\x18\x02 \x01(\tR\bdestPath\"?\n" +
	"\x16WorkloadCopyToResponse\x12%\n" +
	"\x0ebytes_received\x18\x01 \x01(\x03R\rbytesReceived\"H\n" +
	"\x17WorkloadCopyFromRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bsrc_path\x18\x02 \x01(\tR\asrcPath\"+\n" +
	"\x15WorkloadCopyFromChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*\x7f\n" +
	"\fDesiredState\x12\x1d\n" +
	"\x19DESIRED_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DESIRED_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15DESIRED_STATE_STOPPED\x10\x02\x12\x1a\n" +
	"\x16DESIRED_STATE_DELETING\x10\x03*f\n" +
	"\fWorkloadKind\x12\x1d\n" +
	"\x19WORKLOAD_KIND_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKLOAD_KIND_CONTAINER\x10\x01\x12\x1a\n" +
	"\x16WORKLOAD_KIND_MICRO_VM\x10\x02*\x9e\x01\n" +
	"\rWorkloadPhase\x12\x1e\n" +
	"\x1aWORKLOAD_PHASE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_PENDING\x10\x01\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_RUNNING\x10\x02\x12\x19\n" +
	"\x15WORKLOAD_PHASE_FAILED\x10\x03\x12\x1a\n" +
	"\x16WORKLOAD_PHASE_STOPPED\x10\x04*[\n" +
	"\vNetworkMode\x12\x1c\n" +
	"\x18NETWORK_MODE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11NETWORK_MODE_HOST\x10\x01\x12\x17\n" +
	"\x13NETWORK_MODE_BRIDGE\x10\x02*q\n" +
	"\x0eMicroVMBackend\x12 \n" +
	"\x1cMICRO_VM_BACKEND_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cMICRO_VM_BACKEND_FIRECRACKER\x10\x01\x12\x1b\n" +
	"\x17MICRO_VM_BACKEND_SMOLVM\x10\x02*V\n" +
	"\tLogSource\x12\x1a\n" +
	"\x16LOG_SOURCE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12LOG_SOURCE_PAYLOAD\x10\x01\x12\x15\n" +
	"\x11LOG_SOURCE_SERIAL\x10\x022\xf1\x06\n" +
	"\x0fWorkloadService\x12L\n" +
	"\x05Apply\x12 .capsule.v1.WorkloadApplyRequest\x1a!.capsule.v1.WorkloadApplyResponse\x12;\n" +
	"\x03Get\x12\x1e.capsule.v1.WorkloadGetRequest\x1a\x14.capsule.v1.Workload\x12I\n" +
	"\x04List\x12\x1f.capsule.v1.WorkloadListRequest\x1a .capsule.v1.WorkloadListResponse\x12O\n" +
	"\x06Delete\x12!.capsule.v1.WorkloadDeleteRequest\x1a\".capsule.v1.WorkloadDeleteResponse\x12G\n" +
	"\x04Logs\x12\x1f.capsule.v1.WorkloadLogsRequest\x1a\x1c.capsule.v1.WorkloadLogChunk0\x01\x12X\n" +
	"\x04Exec\x12%.capsule.v1.WorkloadExecClientMessage\x1a%.capsule.v1.WorkloadExecServerMessage(\x010\x01\x12R\n" +
	"\aRestart\x12\".capsule.v1.WorkloadRestartRequest\x1a#.capsule.v1.WorkloadRestartResponse\x12I\n" +
	"\x04Stop\x12\x1f.capsule.v1.WorkloadStopRequest\x1a .capsule.v1.WorkloadStopResponse\x12L\n" +
	"\x05Start\x12 .capsule.v1.WorkloadStartRequest\x1a!.capsule.v1.WorkloadStartResponse\x12Q\n" +
	"\x06CopyTo\x12!.capsule.v1.WorkloadCopyToRequest\x1a\".capsule.v1.WorkloadCopyToResponse(\x01\x12T\n" +
	"\bCopyFrom\x12#.capsule.v1.WorkloadCopyFromRequest\x1a!.capsule.v1.WorkloadCopyFromChunk0\x01B\xa6\x01\n" +
	"\x0ecom.capsule.v1B\rWorkloadProtoP\x01Z<github.com/geekgonecrazy/capsule/models/capsule/v1;capsulev1\xa2\x02\x03CXX\xaa\x02\n" +
	"Capsule.V1\xca\x02\n" +
	"Capsule\\V1\xe2\x02\x16Capsule\\V1\\GPBMetadata\xea\x02\vCapsule::V1b\x06proto3"

var (
	file_capsule_v1_workload_proto_rawDescOnce sync.Once
	file_capsule_v1_workload_proto_rawDescData []byte
)

func file_capsule_v1_workload_proto_rawDescGZIP() []byte {
	file_capsule_v1_workload_proto_rawDescOnce.Do(func() {
		file_capsule_v1_workload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capsule_v1_workload_proto_rawDesc), len(file_capsule_v1_workload_proto_rawDesc)))
	})
	return file_capsule_v1_workload_proto_rawDescData
}

var file_capsule_v1_workload_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_capsule_v1_workload_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_capsule_v1_workload_proto_goTypes = []any{
	(DesiredState)(0),                 // 0: capsule.v1.DesiredState
	(WorkloadKind)(0),                 // 1: capsule.v1.WorkloadKind
	(WorkloadPhase)(0),                // 2: capsule.v1.WorkloadPhase
	(NetworkMode)(0),                  // 3: capsule.v1.NetworkMode
	(MicroVMBackend)(0),               // 4: capsule.v1.MicroVMBackend
	(LogSource)(0),                    // 5: capsule.v1.LogSource
	(*Workload)(nil),                  // 6: capsule.v1.Workload
	(*ContainerSpec)(nil),             // 7: capsule.v1.ContainerSpec
	(*PortMapping)(nil),               // 8: capsule.v1.PortMapping
	(*MicroVMSpec)(nil),               // 9: capsule.v1.MicroVMSpec
	(*VolumeMount)(nil),               // 10: capsule.v1.VolumeMount
	(*WorkloadStatus)(nil),            // 11: capsule.v1.WorkloadStatus
	(*WorkloadApplyRequest)(nil),      // 12: capsule.v1.WorkloadApplyRequest
	(*WorkloadApplyResponse)(nil),     // 13: capsule.v1.WorkloadApplyResponse
	(*WorkloadGetRequest)(nil),        // 14: capsule.v1.WorkloadGetRequest
	(*WorkloadListRequest)(nil),       // 15: capsule.v1.WorkloadListRequest
	(*WorkloadListResponse)(nil),      // 16: capsule.v1.WorkloadListResponse
	(*WorkloadDeleteRequest)(nil),     // 17: capsule.v1.WorkloadDeleteRequest
	(*WorkloadDeleteResponse)(nil),    // 18: capsule.v1.WorkloadDeleteResponse
	(*WorkloadLogsRequest)(nil),       // 19: capsule.v1.WorkloadLogsRequest
	(*WorkloadLogChunk)(nil),          // 20: capsule.v1.WorkloadLogChunk
	(*WorkloadExecClientMessage)(nil), // 21: capsule.v1.WorkloadExecClientMessage
	(*WorkloadExecConfig)(nil),        // 22: capsule.v1.WorkloadExecConfig
	(*WorkloadExecResize)(nil),        // 23: capsule.v1.WorkloadExecResize
	(*WorkloadExecServerMessage)(nil), // 24: capsule.v1.WorkloadExecServerMessage
	(*WorkloadExecExit)(nil),          // 25: capsule.v1.WorkloadExecExit
	(*WorkloadRestartRequest)(nil),    // 26: capsule.v1.WorkloadRestartRequest
	(*WorkloadRestartResponse)(nil),   // 27: capsule.v1.WorkloadRestartResponse
	(*WorkloadStopRequest)(nil),       // 28: capsule.v1.WorkloadStopRequest
	(*WorkloadStopResponse)(nil),      // 29: capsule.v1.WorkloadStopResponse
	(*WorkloadStartRequest)(nil),      // 30: capsule.v1.WorkloadStartRequest
	(*WorkloadStartResponse)(nil),     // 31: capsule.v1.WorkloadStartResponse
	(*WorkloadCopyToRequest)(nil),     // 32: capsule.v1.WorkloadCopyToRequest
	(*WorkloadCopyToMetadata)(nil),    // 33: capsule.v1.WorkloadCopyToMetadata
	(*WorkloadCopyToResponse)(nil),    // 34: capsule.v1.WorkloadCopyToResponse
	(*WorkloadCopyFromRequest)(nil),   // 35: capsule.v1.WorkloadCopyFromRequest
	(*WorkloadCopyFromChunk)(nil),     // 36: capsule.v1.WorkloadCopyFromChunk
	nil,                               // 37: capsule.v1.ContainerSpec.EnvEntry
	nil,                               // 38: capsule.v1.MicroVMSpec.EnvEntry
	nil,                               // 39: capsule.v1.WorkloadExecConfig.EnvEntry
}
var file_capsule_v1_workload_proto_depIdxs = []int32{
	1,  // 0: capsule.v1.Workload.kind:type_name -> capsule.v1.WorkloadKind
	7,  // 1: capsule.v1.Workload.container:type_name -> capsule.v1.ContainerSpec
	9,  // 2: capsule.v1.Workload.micro_vm:type_name -> capsule.v1.MicroVMSpec
	11, // 3: capsule.v1.Workload.status:type_name -> capsule.v1.WorkloadStatus
	0,  // 4: capsule.v1.Workload.desired_state:type_name -> capsule.v1.DesiredState
	37, // 5: capsule.v1.ContainerSpec.env:type_name -> capsule.v1.ContainerSpec.EnvEntry
	10, // 6: capsule.v1.ContainerSpec.mounts:type_name -> capsule.v1.VolumeMount
	3,  // 7: capsule.v1.ContainerSpec.network_mode:type_name -> capsule.v1.NetworkMode
	8,  // 8: capsule.v1.ContainerSpec.ports:type_name -> capsule.v1.PortMapping
	38, // 9: capsule.v1.MicroVMSpec.env:type_name -> capsule.v1.MicroVMSpec.EnvEntry
	10, // 10: capsule.v1.MicroVMSpec.mounts:type_name -> capsule.v1.VolumeMount
	4,  // 11: capsule.v1.MicroVMSpec.backend:type_name -> capsule.v1.MicroVMBackend
	8,  // 12: capsule.v1.MicroVMSpec.ports:type_name -> capsule.v1.PortMapping
	2,  // 13: capsule.v1.WorkloadStatus.phase:type_name -> capsule.v1.WorkloadPhase
	6,  // 14: capsule.v1.WorkloadApplyRequest.workload:type_name -> capsule.v1.Workload
	6,  // 15: capsule.v1.WorkloadApplyResponse.workload:type_name -> capsule.v1.Workload
	6,  // 16: capsule.v1.WorkloadListResponse.workloads:type_name -> capsule.v1.Workload
	5,  // 17: capsule.v1.WorkloadLogsRequest.source:type_name -> capsule.v1.LogSource
	22, // 18: capsule.v1.WorkloadExecClientMessage.config:type_name -> capsule.v1.WorkloadExecConfig
	23, // 19: capsule.v1.WorkloadExecClientMessage.resize:type_name -> capsule.v1.WorkloadExecResize
	39, // 20: capsule.v1.WorkloadExecConfig.env:type_name -> capsule.v1.WorkloadExecConfig.EnvEntry
	25, // 21: capsule.v1.WorkloadExecServerMessage.exit:type_name -> capsule.v1.WorkloadExecExit
	33, // 22: capsule.v1.WorkloadCopyToRequest.metadata:type_name -> capsule.v1.WorkloadCopyToMetadata
	12, // 23: capsule.v1.WorkloadService.Apply:input_type -> capsule.v1.WorkloadApplyRequest
	14, // 24: capsule.v1.WorkloadService.Get:input_type -> capsule.v1.WorkloadGetRequest
	15, // 25: capsule.v1.WorkloadService.List:input_type -> capsule.v1.WorkloadListRequest
	17, // 26: capsule.v1.WorkloadService.Delete:input_type -> capsule.v1.WorkloadDeleteRequest
	19, // 27: capsule.v1.WorkloadService.Logs:input_type -> capsule.v1.WorkloadLogsRequest
	21, // 28: capsule.v1.WorkloadService.Exec:input_type -> capsule.v1.WorkloadExecClientMessage
	26, // 29: capsule.v1.WorkloadService.Restart:input_type -> capsule.v1.WorkloadRestartRequest
	28, // 30: capsule.v1.WorkloadService.Stop:input_type -> capsule.v1.WorkloadStopRequest
	30, // 31: capsule.v1.WorkloadService.Start:input_type -> capsule.v1.WorkloadStartRequest
	32, // 32: capsule.v1.WorkloadService.CopyTo:input_type -> capsule.v1.WorkloadCopyToRequest
	35, // 33: capsule.v1.WorkloadService.CopyFrom:input_type -> capsule.v1.WorkloadCopyFromRequest
	13, // 34: capsule.v1.WorkloadService.Apply:output_type -> capsule.v1.WorkloadApplyResponse
	6,  // 35: capsule.v1.WorkloadService.Get:output_type -> capsule.v1.Workload
	16, // 36: capsule.v1.WorkloadService.List:output_type -> capsule.v1.WorkloadListResponse
	18, // 37: capsule.v1.WorkloadService.Delete:output_type -> capsule.v1.WorkloadDeleteResponse
	20, // 38: capsule.v1.WorkloadService.Logs:output_type -> capsule.v1.WorkloadLogChunk
	24, // 39: capsule.v1.WorkloadService.Exec:output_type -> capsule.v1.WorkloadExecServerMessage
	27, // 40: capsule.v1.WorkloadService.Restart:output_type -> capsule.v1.WorkloadRestartResponse
	29, // 41: capsule.v1.WorkloadService.Stop:output_type -> capsule.v1.WorkloadStopResponse
	31, // 42: capsule.v1.WorkloadService.Start:output_type -> capsule.v1.WorkloadStartResponse
	34, // 43: capsule.v1.WorkloadService.CopyTo:output_type -> capsule.v1.WorkloadCopyToResponse
	36, // 44: capsule.v1.WorkloadService.CopyFrom:output_type -> capsule.v1.WorkloadCopyFromChunk
	34, // [34:45] is the sub-list for method output_type
	23, // [23:34] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_capsule_v1_workload_proto_init() }
func file_capsule_v1_workload_proto_init() {
	if File_capsule_v1_workload_proto != nil {
		return
	}
	file_capsule_v1_workload_proto_msgTypes[15].OneofWrappers = []any{
		(*WorkloadExecClientMessage_Config)(nil),
		(*WorkloadExecClientMessage_Stdin)(nil),
		(*WorkloadExecClientMessage_Resize)(nil),
	}
	file_capsule_v1_workload_proto_msgTypes[18].OneofWrappers = []any{
		(*WorkloadExecServerMessage_Stdout)(nil),
		(*WorkloadExecServerMessage_Stderr)(nil),
		(*WorkloadExecServerMessage_Exit)(nil),
	}
	file_capsule_v1_workload_proto_msgTypes[26].OneofWrappers = []any{
		(*WorkloadCopyToRequest_Metadata)(nil),
		(*WorkloadCopyToRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capsule_v1_workload_proto_rawDesc), len(file_capsule_v1_workload_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capsule_v1_workload_proto_goTypes,
		DependencyIndexes: file_capsule_v1_workload_proto_depIdxs,
		EnumInfos:         file_capsule_v1_workload_proto_enumTypes,
		MessageInfos:      file_capsule_v1_workload_proto_msgTypes,
	}.Build()
	File_capsule_v1_workload_proto = out.File
	file_capsule_v1_workload_proto_goTypes = nil
	file_capsule_v1_workload_proto_depIdxs = nil
}
